// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: calendars.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCalendarConnection = `-- name: DeleteCalendarConnection :exec
DELETE FROM calendar_connections
WHERE user_id = $1 AND provider = $2
`

type DeleteCalendarConnectionParams struct {
	UserID   string `json:"user_id"`
	Provider string `json:"provider"`
}

func (q *Queries) DeleteCalendarConnection(ctx context.Context, arg DeleteCalendarConnectionParams) error {
	_, err := q.db.Exec(ctx, deleteCalendarConnection, arg.UserID, arg.Provider)
	return err
}

const getCalendarConnection = `-- name: GetCalendarConnection :one
SELECT id, user_id, provider, account_label, access_token, refresh_token, token_expiry, ical_url, created_at
FROM calendar_connections
WHERE user_id = $1 AND provider = $2
`

type GetCalendarConnectionParams struct {
	UserID   string `json:"user_id"`
	Provider string `json:"provider"`
}

func (q *Queries) GetCalendarConnection(ctx context.Context, arg GetCalendarConnectionParams) (CalendarConnection, error) {
	row := q.db.QueryRow(ctx, getCalendarConnection, arg.UserID, arg.Provider)
	var i CalendarConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.AccountLabel,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiry,
		&i.IcalUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listCalendarConnections = `-- name: ListCalendarConnections :many

SELECT id, user_id, provider, account_label, access_token, refresh_token, token_expiry, ical_url, created_at
FROM calendar_connections
WHERE user_id = $1
ORDER BY provider
`

// ======================== calendar connections ====================
func (q *Queries) ListCalendarConnections(ctx context.Context, userID string) ([]CalendarConnection, error) {
	rows, err := q.db.Query(ctx, listCalendarConnections, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarConnection{}
	for rows.Next() {
		var i CalendarConnection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.AccountLabel,
			&i.AccessToken,
			&i.RefreshToken,
			&i.TokenExpiry,
			&i.IcalUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCalendarTokens = `-- name: UpdateCalendarTokens :exec
UPDATE calendar_connections
SET access_token = $3, refresh_token = $4, token_expiry = $5
WHERE user_id = $1 AND provider = $2
`

type UpdateCalendarTokensParams struct {
	UserID       string             `json:"user_id"`
	Provider     string             `json:"provider"`
	AccessToken  string             `json:"access_token"`
	RefreshToken string             `json:"refresh_token"`
	TokenExpiry  pgtype.Timestamptz `json:"token_expiry"`
}

func (q *Queries) UpdateCalendarTokens(ctx context.Context, arg UpdateCalendarTokensParams) error {
	_, err := q.db.Exec(ctx, updateCalendarTokens,
		arg.UserID,
		arg.Provider,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiry,
	)
	return err
}

const upsertCalendarConnection = `-- name: UpsertCalendarConnection :one
INSERT INTO calendar_connections (user_id, provider, account_label, access_token, refresh_token, token_expiry, ical_url)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id, provider) DO UPDATE
    SET account_label = EXCLUDED.account_label,
        access_token  = EXCLUDED.access_token,
        refresh_token = EXCLUDED.refresh_token,
        token_expiry  = EXCLUDED.token_expiry,
        ical_url      = EXCLUDED.ical_url
RETURNING id, user_id, provider, account_label, access_token, refresh_token, token_expiry, ical_url, created_at
`

type UpsertCalendarConnectionParams struct {
	UserID       string             `json:"user_id"`
	Provider     string             `json:"provider"`
	AccountLabel string             `json:"account_label"`
	AccessToken  string             `json:"access_token"`
	RefreshToken string             `json:"refresh_token"`
	TokenExpiry  pgtype.Timestamptz `json:"token_expiry"`
	IcalUrl      string             `json:"ical_url"`
}

func (q *Queries) UpsertCalendarConnection(ctx context.Context, arg UpsertCalendarConnectionParams) (CalendarConnection, error) {
	row := q.db.QueryRow(ctx, upsertCalendarConnection,
		arg.UserID,
		arg.Provider,
		arg.AccountLabel,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiry,
		arg.IcalUrl,
	)
	var i CalendarConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.AccountLabel,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiry,
		&i.IcalUrl,
		&i.CreatedAt,
	)
	return i, err
}
