// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCohost = `-- name: AddCohost :exec
INSERT INTO event_cohosts (event_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddCohostParams struct {
	EventID pgtype.UUID `json:"event_id"`
	UserID  string      `json:"user_id"`
}

func (q *Queries) AddCohost(ctx context.Context, arg AddCohostParams) error {
	_, err := q.db.Exec(ctx, addCohost, arg.EventID, arg.UserID)
	return err
}

const addEventComment = `-- name: AddEventComment :one
INSERT INTO event_comments (event_id, user_id, body, gif_url)
VALUES ($1, $2, $3, $4)
RETURNING id, event_id, user_id, body, gif_url, created_at
`

type AddEventCommentParams struct {
	EventID pgtype.UUID `json:"event_id"`
	UserID  string      `json:"user_id"`
	Body    string      `json:"body"`
	GifUrl  string      `json:"gif_url"`
}

type AddEventCommentRow struct {
	ID        pgtype.UUID        `json:"id"`
	EventID   pgtype.UUID        `json:"event_id"`
	UserID    string             `json:"user_id"`
	Body      string             `json:"body"`
	GifUrl    string             `json:"gif_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) AddEventComment(ctx context.Context, arg AddEventCommentParams) (AddEventCommentRow, error) {
	row := q.db.QueryRow(ctx, addEventComment,
		arg.EventID,
		arg.UserID,
		arg.Body,
		arg.GifUrl,
	)
	var i AddEventCommentRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Body,
		&i.GifUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEventComment = `-- name: DeleteEventComment :exec
DELETE FROM event_comments WHERE id = $1
`

func (q *Queries) DeleteEventComment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEventComment, id)
	return err
}

const getEventComment = `-- name: GetEventComment :one
SELECT id, event_id, user_id, body, created_at
FROM event_comments
WHERE id = $1
`

type GetEventCommentRow struct {
	ID        pgtype.UUID        `json:"id"`
	EventID   pgtype.UUID        `json:"event_id"`
	UserID    string             `json:"user_id"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetEventComment(ctx context.Context, id pgtype.UUID) (GetEventCommentRow, error) {
	row := q.db.QueryRow(ctx, getEventComment, id)
	var i GetEventCommentRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const isCohost = `-- name: IsCohost :one
SELECT EXISTS (
    SELECT 1 FROM event_cohosts WHERE event_id = $1 AND user_id = $2
)
`

type IsCohostParams struct {
	EventID pgtype.UUID `json:"event_id"`
	UserID  string      `json:"user_id"`
}

func (q *Queries) IsCohost(ctx context.Context, arg IsCohostParams) (bool, error) {
	row := q.db.QueryRow(ctx, isCohost, arg.EventID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listCohosts = `-- name: ListCohosts :many

SELECT ch.user_id, ch.created_at, p.display_name, p.handle, p.avatar_url
FROM event_cohosts ch
LEFT JOIN profiles p ON p.user_id = ch.user_id
WHERE ch.event_id = $1
ORDER BY ch.created_at
`

type ListCohostsRow struct {
	UserID      string             `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	DisplayName pgtype.Text        `json:"display_name"`
	Handle      pgtype.Text        `json:"handle"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
}

// ========================== event cohosts =========================
func (q *Queries) ListCohosts(ctx context.Context, eventID pgtype.UUID) ([]ListCohostsRow, error) {
	rows, err := q.db.Query(ctx, listCohosts, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCohostsRow{}
	for rows.Next() {
		var i ListCohostsRow
		if err := rows.Scan(
			&i.UserID,
			&i.CreatedAt,
			&i.DisplayName,
			&i.Handle,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventComments = `-- name: ListEventComments :many

SELECT c.id, c.event_id, c.user_id, c.body, c.gif_url, c.created_at,
       p.display_name, p.avatar_url
FROM event_comments c
LEFT JOIN profiles p ON p.user_id = c.user_id
WHERE c.event_id = $1
ORDER BY c.created_at
`

type ListEventCommentsRow struct {
	ID          pgtype.UUID        `json:"id"`
	EventID     pgtype.UUID        `json:"event_id"`
	UserID      string             `json:"user_id"`
	Body        string             `json:"body"`
	GifUrl      string             `json:"gif_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	DisplayName pgtype.Text        `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
}

// ========================= event comments =========================
func (q *Queries) ListEventComments(ctx context.Context, eventID pgtype.UUID) ([]ListEventCommentsRow, error) {
	rows, err := q.db.Query(ctx, listEventComments, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventCommentsRow{}
	for rows.Next() {
		var i ListEventCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.UserID,
			&i.Body,
			&i.GifUrl,
			&i.CreatedAt,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCohost = `-- name: RemoveCohost :exec
DELETE FROM event_cohosts WHERE event_id = $1 AND user_id = $2
`

type RemoveCohostParams struct {
	EventID pgtype.UUID `json:"event_id"`
	UserID  string      `json:"user_id"`
}

func (q *Queries) RemoveCohost(ctx context.Context, arg RemoveCohostParams) error {
	_, err := q.db.Exec(ctx, removeCohost, arg.EventID, arg.UserID)
	return err
}
