// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customtypes.sql

package db

import (
	"context"
)

const deleteCustomType = `-- name: DeleteCustomType :exec
DELETE FROM custom_event_types
WHERE user_id = $1 AND label = $2
`

type DeleteCustomTypeParams struct {
	UserID string `json:"user_id"`
	Label  string `json:"label"`
}

func (q *Queries) DeleteCustomType(ctx context.Context, arg DeleteCustomTypeParams) error {
	_, err := q.db.Exec(ctx, deleteCustomType, arg.UserID, arg.Label)
	return err
}

const listCustomTypes = `-- name: ListCustomTypes :many
SELECT label, emoji FROM custom_event_types
WHERE user_id = $1
ORDER BY created_at
`

type ListCustomTypesRow struct {
	Label string `json:"label"`
	Emoji string `json:"emoji"`
}

func (q *Queries) ListCustomTypes(ctx context.Context, userID string) ([]ListCustomTypesRow, error) {
	rows, err := q.db.Query(ctx, listCustomTypes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustomTypesRow{}
	for rows.Next() {
		var i ListCustomTypesRow
		if err := rows.Scan(&i.Label, &i.Emoji); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCustomType = `-- name: UpsertCustomType :exec

INSERT INTO custom_event_types (user_id, label, emoji)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, label) DO UPDATE SET emoji = EXCLUDED.emoji
`

type UpsertCustomTypeParams struct {
	UserID string `json:"user_id"`
	Label  string `json:"label"`
	Emoji  string `json:"emoji"`
}

// ====================== custom event types ========================
func (q *Queries) UpsertCustomType(ctx context.Context, arg UpsertCustomTypeParams) error {
	_, err := q.db.Exec(ctx, upsertCustomType, arg.UserID, arg.Label, arg.Emoji)
	return err
}
