// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discover.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFollow = `-- name: AddFollow :exec

INSERT INTO follows (user_id, kind, value)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddFollowParams struct {
	UserID string `json:"user_id"`
	Kind   string `json:"kind"`
	Value  string `json:"value"`
}

// ========================== follows ===============================
func (q *Queries) AddFollow(ctx context.Context, arg AddFollowParams) error {
	_, err := q.db.Exec(ctx, addFollow, arg.UserID, arg.Kind, arg.Value)
	return err
}

const countFriendGoingForPublicUpcoming = `-- name: CountFriendGoingForPublicUpcoming :many
SELECT a.event_id, count(*)::int AS going
FROM event_attendees a
JOIN events e ON e.id = a.event_id
WHERE e.visibility = 'public' AND e.status = 'scheduled' AND e.starts_at >= now()
  AND a.rsvp = 'going' AND a.user_id = ANY($1::text[])
GROUP BY a.event_id
`

type CountFriendGoingForPublicUpcomingRow struct {
	EventID pgtype.UUID `json:"event_id"`
	Going   int32       `json:"going"`
}

func (q *Queries) CountFriendGoingForPublicUpcoming(ctx context.Context, dollar_1 []string) ([]CountFriendGoingForPublicUpcomingRow, error) {
	rows, err := q.db.Query(ctx, countFriendGoingForPublicUpcoming, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountFriendGoingForPublicUpcomingRow{}
	for rows.Next() {
		var i CountFriendGoingForPublicUpcomingRow
		if err := rows.Scan(&i.EventID, &i.Going); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countGoingForPublicUpcoming = `-- name: CountGoingForPublicUpcoming :many
SELECT a.event_id, count(*)::int AS going
FROM event_attendees a
JOIN events e ON e.id = a.event_id
WHERE e.visibility = 'public' AND e.status = 'scheduled' AND e.starts_at >= now()
  AND a.rsvp = 'going'
GROUP BY a.event_id
`

type CountGoingForPublicUpcomingRow struct {
	EventID pgtype.UUID `json:"event_id"`
	Going   int32       `json:"going"`
}

func (q *Queries) CountGoingForPublicUpcoming(ctx context.Context) ([]CountGoingForPublicUpcomingRow, error) {
	rows, err := q.db.Query(ctx, countGoingForPublicUpcoming)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountGoingForPublicUpcomingRow{}
	for rows.Next() {
		var i CountGoingForPublicUpcomingRow
		if err := rows.Scan(&i.EventID, &i.Going); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsNeedingReminder = `-- name: ListEventsNeedingReminder :many

SELECT id, host_id, title, event_type, description,
       location_mode, location_address, scheduling_mode, starts_at, status, created_at, comments_enabled, group_id, series_id, recurrence, reminder_sent, visibility, topic, city, custom_emoji, custom_label
FROM events
WHERE status = 'scheduled' AND reminder_sent = false
  AND starts_at > now() AND starts_at <= now() + interval '24 hours'
`

// ==================== reminders (cron) ============================
func (q *Queries) ListEventsNeedingReminder(ctx context.Context) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsNeedingReminder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Title,
			&i.EventType,
			&i.Description,
			&i.LocationMode,
			&i.LocationAddress,
			&i.SchedulingMode,
			&i.StartsAt,
			&i.Status,
			&i.CreatedAt,
			&i.CommentsEnabled,
			&i.GroupID,
			&i.SeriesID,
			&i.Recurrence,
			&i.ReminderSent,
			&i.Visibility,
			&i.Topic,
			&i.City,
			&i.CustomEmoji,
			&i.CustomLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedEvents = `-- name: ListFeedEvents :many
SELECT e.id, e.title, e.event_type, e.starts_at, e.topic, e.city,
       p.display_name AS host_name, p.avatar_url AS host_avatar, e.host_id
FROM events e
LEFT JOIN profiles p ON p.user_id = e.host_id
WHERE e.visibility = 'public' AND e.status = 'scheduled' AND e.starts_at >= now()
  AND (e.host_id IN (SELECT value FROM follows f WHERE f.user_id = $1 AND kind = 'host')
    OR (e.topic <> '' AND e.topic IN (SELECT value FROM follows f WHERE f.user_id = $1 AND kind = 'topic')))
ORDER BY e.starts_at NULLS LAST
LIMIT 100
`

type ListFeedEventsRow struct {
	ID         pgtype.UUID        `json:"id"`
	Title      string             `json:"title"`
	EventType  string             `json:"event_type"`
	StartsAt   pgtype.Timestamptz `json:"starts_at"`
	Topic      string             `json:"topic"`
	City       string             `json:"city"`
	HostName   pgtype.Text        `json:"host_name"`
	HostAvatar pgtype.Text        `json:"host_avatar"`
	HostID     string             `json:"host_id"`
}

func (q *Queries) ListFeedEvents(ctx context.Context, userID string) ([]ListFeedEventsRow, error) {
	rows, err := q.db.Query(ctx, listFeedEvents, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeedEventsRow{}
	for rows.Next() {
		var i ListFeedEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.EventType,
			&i.StartsAt,
			&i.Topic,
			&i.City,
			&i.HostName,
			&i.HostAvatar,
			&i.HostID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollows = `-- name: ListFollows :many
SELECT kind, value FROM follows WHERE user_id = $1 ORDER BY created_at
`

type ListFollowsRow struct {
	Kind  string `json:"kind"`
	Value string `json:"value"`
}

func (q *Queries) ListFollows(ctx context.Context, userID string) ([]ListFollowsRow, error) {
	rows, err := q.db.Query(ctx, listFollows, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowsRow{}
	for rows.Next() {
		var i ListFollowsRow
		if err := rows.Scan(&i.Kind, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFriendIDs = `-- name: ListFriendIDs :many
SELECT (CASE WHEN f.requester_id = $1 THEN f.addressee_id ELSE f.requester_id END)::text AS friend_id
FROM friendships f
WHERE f.status = 'accepted' AND (f.requester_id = $1 OR f.addressee_id = $1)
`

func (q *Queries) ListFriendIDs(ctx context.Context, requesterID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listFriendIDs, requesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var friend_id string
		if err := rows.Scan(&friend_id); err != nil {
			return nil, err
		}
		items = append(items, friend_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFriendsEvents = `-- name: ListFriendsEvents :many
SELECT e.id, e.title, e.event_type, e.starts_at, e.topic, e.city,
       p.display_name AS host_name, p.avatar_url AS host_avatar, e.host_id, e.custom_emoji, e.custom_label,
       (SELECT count(*)::int FROM event_attendees a
          JOIN friendships f ON f.status = 'accepted'
           AND ((f.requester_id = $1::text AND f.addressee_id = a.user_id)
             OR (f.addressee_id = $1::text AND f.requester_id = a.user_id))
        WHERE a.event_id = e.id AND a.rsvp = 'going') AS friends_going,
       COALESCE((SELECT a2.rsvp FROM event_attendees a2 WHERE a2.event_id = e.id AND a2.user_id = $1::text), '')::text AS viewer_rsvp,
       (EXISTS(SELECT 1 FROM friendships f2 WHERE f2.status = 'accepted'
           AND ((f2.requester_id = $1::text AND f2.addressee_id = e.host_id)
             OR (f2.addressee_id = $1::text AND f2.requester_id = e.host_id))))::bool AS from_friend
FROM events e
LEFT JOIN profiles p ON p.user_id = e.host_id
WHERE e.status IN ('polling', 'scheduled')
  AND (e.starts_at IS NULL OR e.starts_at >= now())
  AND e.visibility IN ('friends', 'public')
  AND e.host_id IN (
      SELECT (CASE WHEN f.requester_id = $1 THEN f.addressee_id ELSE f.requester_id END)::text
      FROM friendships f
      WHERE f.status = 'accepted' AND (f.requester_id = $1 OR f.addressee_id = $1))
ORDER BY e.starts_at NULLS LAST
LIMIT 100
`

type ListFriendsEventsRow struct {
	ID           pgtype.UUID        `json:"id"`
	Title        string             `json:"title"`
	EventType    string             `json:"event_type"`
	StartsAt     pgtype.Timestamptz `json:"starts_at"`
	Topic        string             `json:"topic"`
	City         string             `json:"city"`
	HostName     pgtype.Text        `json:"host_name"`
	HostAvatar   pgtype.Text        `json:"host_avatar"`
	HostID       string             `json:"host_id"`
	CustomEmoji  string             `json:"custom_emoji"`
	CustomLabel  string             `json:"custom_label"`
	FriendsGoing int32              `json:"friends_going"`
	ViewerRsvp   string             `json:"viewer_rsvp"`
	FromFriend   bool               `json:"from_friend"`
}

func (q *Queries) ListFriendsEvents(ctx context.Context, dollar_1 string) ([]ListFriendsEventsRow, error) {
	rows, err := q.db.Query(ctx, listFriendsEvents, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFriendsEventsRow{}
	for rows.Next() {
		var i ListFriendsEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.EventType,
			&i.StartsAt,
			&i.Topic,
			&i.City,
			&i.HostName,
			&i.HostAvatar,
			&i.HostID,
			&i.CustomEmoji,
			&i.CustomLabel,
			&i.FriendsGoing,
			&i.ViewerRsvp,
			&i.FromFriend,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeopleYouMayKnow = `-- name: ListPeopleYouMayKnow :many
SELECT
    other.user_id AS friend_id,
    p.display_name,
    p.handle,
    p.avatar_url,
    SUM(
        (CASE e.visibility WHEN 'public' THEN 1 WHEN 'friends' THEN 3 ELSE 4 END)
        + (CASE WHEN me.rsvp = 'going' AND other.rsvp = 'going'
                THEN (CASE e.visibility WHEN 'public' THEN 1 WHEN 'friends' THEN 3 ELSE 4 END)
                ELSE 0 END)
    )::int AS score,
    COUNT(DISTINCT e.id)::int AS shared_events
FROM event_attendees me
JOIN event_attendees other ON other.event_id = me.event_id AND other.user_id <> me.user_id
JOIN events e ON e.id = me.event_id
JOIN profiles p ON p.user_id = other.user_id
WHERE me.user_id = $1
  AND me.rsvp IN ('going', 'maybe')
  AND other.rsvp IN ('going', 'maybe')
  AND other.user_id NOT LIKE 'guest_%'
  AND NOT EXISTS (
      SELECT 1 FROM friendships f
      WHERE (f.requester_id = $1 AND f.addressee_id = other.user_id)
         OR (f.addressee_id = $1 AND f.requester_id = other.user_id))
GROUP BY other.user_id, p.display_name, p.handle, p.avatar_url
ORDER BY score DESC, shared_events DESC
LIMIT 12
`

type ListPeopleYouMayKnowRow struct {
	FriendID     string `json:"friend_id"`
	DisplayName  string `json:"display_name"`
	Handle       string `json:"handle"`
	AvatarUrl    string `json:"avatar_url"`
	Score        int32  `json:"score"`
	SharedEvents int32  `json:"shared_events"`
}

// Suggests people you've co-attended events with, ranked by how meaningful the
// overlap is: a shared public event is the weakest signal; both being "going"
// to a friends-only or invite-only (link) event is the strongest. Excludes
// yourself, guests, and anyone you already have a friendship/request with.
func (q *Queries) ListPeopleYouMayKnow(ctx context.Context, userID string) ([]ListPeopleYouMayKnowRow, error) {
	rows, err := q.db.Query(ctx, listPeopleYouMayKnow, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPeopleYouMayKnowRow{}
	for rows.Next() {
		var i ListPeopleYouMayKnowRow
		if err := rows.Scan(
			&i.FriendID,
			&i.DisplayName,
			&i.Handle,
			&i.AvatarUrl,
			&i.Score,
			&i.SharedEvents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicEvents = `-- name: ListPublicEvents :many

SELECT e.id, e.title, e.event_type, e.starts_at, e.topic, e.city,
       p.display_name AS host_name, p.avatar_url AS host_avatar, e.host_id, e.custom_emoji, e.custom_label,
       (SELECT count(*)::int FROM event_attendees a
          JOIN friendships f ON f.status = 'accepted'
           AND ((f.requester_id = $3::text AND f.addressee_id = a.user_id)
             OR (f.addressee_id = $3::text AND f.requester_id = a.user_id))
        WHERE a.event_id = e.id AND a.rsvp = 'going') AS friends_going,
       COALESCE((SELECT a2.rsvp FROM event_attendees a2 WHERE a2.event_id = e.id AND a2.user_id = $3::text), '')::text AS viewer_rsvp,
       (EXISTS(SELECT 1 FROM friendships f2 WHERE f2.status = 'accepted'
           AND ((f2.requester_id = $3::text AND f2.addressee_id = e.host_id)
             OR (f2.addressee_id = $3::text AND f2.requester_id = e.host_id))))::bool AS from_friend
FROM events e
LEFT JOIN profiles p ON p.user_id = e.host_id
WHERE e.status IN ('polling', 'scheduled')
  AND (e.starts_at IS NULL OR e.starts_at >= now())
  AND (e.visibility = 'public'
    OR ($3::text <> '' AND e.visibility = 'friends' AND EXISTS(
        SELECT 1 FROM friendships ff WHERE ff.status = 'accepted'
          AND ((ff.requester_id = $3 AND ff.addressee_id = e.host_id)
            OR (ff.addressee_id = $3 AND ff.requester_id = e.host_id)))))
  AND ($1::text = '' OR e.topic = $1)
  AND (cardinality($2::text[]) = 0 OR e.city ILIKE ANY($2::text[]))
ORDER BY e.starts_at NULLS LAST
LIMIT 100
`

type ListPublicEventsParams struct {
	Column1 string   `json:"column_1"`
	Column2 []string `json:"column_2"`
	Column3 string   `json:"column_3"`
}

type ListPublicEventsRow struct {
	ID           pgtype.UUID        `json:"id"`
	Title        string             `json:"title"`
	EventType    string             `json:"event_type"`
	StartsAt     pgtype.Timestamptz `json:"starts_at"`
	Topic        string             `json:"topic"`
	City         string             `json:"city"`
	HostName     pgtype.Text        `json:"host_name"`
	HostAvatar   pgtype.Text        `json:"host_avatar"`
	HostID       string             `json:"host_id"`
	CustomEmoji  string             `json:"custom_emoji"`
	CustomLabel  string             `json:"custom_label"`
	FriendsGoing int32              `json:"friends_going"`
	ViewerRsvp   string             `json:"viewer_rsvp"`
	FromFriend   bool               `json:"from_friend"`
}

// ==================== public discovery ============================
func (q *Queries) ListPublicEvents(ctx context.Context, arg ListPublicEventsParams) ([]ListPublicEventsRow, error) {
	rows, err := q.db.Query(ctx, listPublicEvents, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicEventsRow{}
	for rows.Next() {
		var i ListPublicEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.EventType,
			&i.StartsAt,
			&i.Topic,
			&i.City,
			&i.HostName,
			&i.HostAvatar,
			&i.HostID,
			&i.CustomEmoji,
			&i.CustomLabel,
			&i.FriendsGoing,
			&i.ViewerRsvp,
			&i.FromFriend,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRsvpHistory = `-- name: ListUserRsvpHistory :many

SELECT e.host_id, e.topic, e.event_type
FROM event_attendees a
JOIN events e ON e.id = a.event_id
WHERE a.user_id = $1 AND a.rsvp IN ('going', 'maybe')
ORDER BY a.created_at DESC
LIMIT 200
`

type ListUserRsvpHistoryRow struct {
	HostID    string `json:"host_id"`
	Topic     string `json:"topic"`
	EventType string `json:"event_type"`
}

// ==================== feed ranking signals =========================
func (q *Queries) ListUserRsvpHistory(ctx context.Context, userID string) ([]ListUserRsvpHistoryRow, error) {
	rows, err := q.db.Query(ctx, listUserRsvpHistory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserRsvpHistoryRow{}
	for rows.Next() {
		var i ListUserRsvpHistoryRow
		if err := rows.Scan(&i.HostID, &i.Topic, &i.EventType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEventReminded = `-- name: MarkEventReminded :exec
UPDATE events SET reminder_sent = true WHERE id = $1
`

func (q *Queries) MarkEventReminded(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEventReminded, id)
	return err
}

const removeFollow = `-- name: RemoveFollow :exec
DELETE FROM follows WHERE user_id = $1 AND kind = $2 AND value = $3
`

type RemoveFollowParams struct {
	UserID string `json:"user_id"`
	Kind   string `json:"kind"`
	Value  string `json:"value"`
}

func (q *Queries) RemoveFollow(ctx context.Context, arg RemoveFollowParams) error {
	_, err := q.db.Exec(ctx, removeFollow, arg.UserID, arg.Kind, arg.Value)
	return err
}
