// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addGroupMember = `-- name: AddGroupMember :exec
INSERT INTO group_members (group_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddGroupMemberParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  string      `json:"user_id"`
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error {
	_, err := q.db.Exec(ctx, addGroupMember, arg.GroupID, arg.UserID)
	return err
}

const countGroupMembers = `-- name: CountGroupMembers :one
SELECT count(*)::int FROM group_members WHERE group_id = $1
`

func (q *Queries) CountGroupMembers(ctx context.Context, groupID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countGroupMembers, groupID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createGroup = `-- name: CreateGroup :one

INSERT INTO groups (owner_id, name, emoji)
VALUES ($1, $2, $3)
RETURNING id, owner_id, name, emoji, created_at, icon_url
`

type CreateGroupParams struct {
	OwnerID string `json:"owner_id"`
	Name    string `json:"name"`
	Emoji   string `json:"emoji"`
}

// ============================ groups ==============================
func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.OwnerID, arg.Name, arg.Emoji)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Emoji,
		&i.CreatedAt,
		&i.IconUrl,
	)
	return i, err
}

const getGroup = `-- name: GetGroup :one
SELECT id, owner_id, name, emoji, created_at, icon_url
FROM groups
WHERE id = $1
`

func (q *Queries) GetGroup(ctx context.Context, id pgtype.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Emoji,
		&i.CreatedAt,
		&i.IconUrl,
	)
	return i, err
}

const isGroupMember = `-- name: IsGroupMember :one
SELECT EXISTS (
    SELECT 1 FROM groups g
    LEFT JOIN group_members m ON m.group_id = g.id AND m.user_id = $2
    WHERE g.id = $1 AND (g.owner_id = $2 OR m.user_id IS NOT NULL)
)
`

type IsGroupMemberParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) IsGroupMember(ctx context.Context, arg IsGroupMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isGroupMember, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listGoingAttendeeEmails = `-- name: ListGoingAttendeeEmails :many
SELECT p.email
FROM event_attendees a
JOIN profiles p ON p.user_id = a.user_id
WHERE a.event_id = $1 AND a.rsvp = 'going' AND p.email <> ''
`

func (q *Queries) ListGoingAttendeeEmails(ctx context.Context, eventID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listGoingAttendeeEmails, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var email string
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupEventMonths = `-- name: ListGroupEventMonths :many
SELECT group_id, starts_at FROM events
WHERE group_id IS NOT NULL AND status = 'scheduled'
  AND starts_at IS NOT NULL AND starts_at <= now()
`

type ListGroupEventMonthsRow struct {
	GroupID  pgtype.UUID        `json:"group_id"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
}

// Start times of every HAPPENED scheduled group event - the cron computes
// month streaks from these (mirrors the web's groupStreak, which also counts
// this month's still-upcoming events; the email celebrates only real ones).
func (q *Queries) ListGroupEventMonths(ctx context.Context) ([]ListGroupEventMonthsRow, error) {
	rows, err := q.db.Query(ctx, listGroupEventMonths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupEventMonthsRow{}
	for rows.Next() {
		var i ListGroupEventMonthsRow
		if err := rows.Scan(&i.GroupID, &i.StartsAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupEvents = `-- name: ListGroupEvents :many
SELECT id, host_id, title, event_type, description,
       location_mode, location_address, scheduling_mode, starts_at, status, created_at, comments_enabled, group_id, series_id, recurrence, reminder_sent, visibility, topic, city, custom_emoji, custom_label, general_scope, photo_url, theme, timezone, ends_at, poll_deadline, poll_ready_sent, vote_reminder_sent, quorum_sent, capacity
FROM events
WHERE group_id = $1 AND status <> 'cancelled'
ORDER BY created_at DESC
`

func (q *Queries) ListGroupEvents(ctx context.Context, groupID pgtype.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, listGroupEvents, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Title,
			&i.EventType,
			&i.Description,
			&i.LocationMode,
			&i.LocationAddress,
			&i.SchedulingMode,
			&i.StartsAt,
			&i.Status,
			&i.CreatedAt,
			&i.CommentsEnabled,
			&i.GroupID,
			&i.SeriesID,
			&i.Recurrence,
			&i.ReminderSent,
			&i.Visibility,
			&i.Topic,
			&i.City,
			&i.CustomEmoji,
			&i.CustomLabel,
			&i.GeneralScope,
			&i.PhotoUrl,
			&i.Theme,
			&i.Timezone,
			&i.EndsAt,
			&i.PollDeadline,
			&i.PollReadySent,
			&i.VoteReminderSent,
			&i.QuorumSent,
			&i.Capacity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMemberContacts = `-- name: ListGroupMemberContacts :many
SELECT p.user_id, p.display_name, p.email
FROM group_members m
JOIN profiles p ON p.user_id = m.user_id
WHERE m.group_id = $1 AND p.email <> ''
`

type ListGroupMemberContactsRow struct {
	UserID      string `json:"user_id"`
	DisplayName string `json:"display_name"`
	Email       string `json:"email"`
}

func (q *Queries) ListGroupMemberContacts(ctx context.Context, groupID pgtype.UUID) ([]ListGroupMemberContactsRow, error) {
	rows, err := q.db.Query(ctx, listGroupMemberContacts, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupMemberContactsRow{}
	for rows.Next() {
		var i ListGroupMemberContactsRow
		if err := rows.Scan(&i.UserID, &i.DisplayName, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT m.user_id, m.created_at, p.display_name, p.handle, p.avatar_url
FROM group_members m
LEFT JOIN profiles p ON p.user_id = m.user_id
WHERE m.group_id = $1
ORDER BY m.created_at
`

type ListGroupMembersRow struct {
	UserID      string             `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	DisplayName pgtype.Text        `json:"display_name"`
	Handle      pgtype.Text        `json:"handle"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) ListGroupMembers(ctx context.Context, groupID pgtype.UUID) ([]ListGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupMembersRow{}
	for rows.Next() {
		var i ListGroupMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.CreatedAt,
			&i.DisplayName,
			&i.Handle,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyGroups = `-- name: ListMyGroups :many
SELECT DISTINCT g.id, g.owner_id, g.name, g.emoji, g.created_at, g.icon_url
FROM groups g
LEFT JOIN group_members m ON m.group_id = g.id
WHERE g.owner_id = $1 OR m.user_id = $1
ORDER BY g.created_at DESC
`

func (q *Queries) ListMyGroups(ctx context.Context, ownerID string) ([]Group, error) {
	rows, err := q.db.Query(ctx, listMyGroups, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Emoji,
			&i.CreatedAt,
			&i.IconUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStreakCongrats = `-- name: MarkStreakCongrats :one
INSERT INTO group_streak_congrats (group_id, month) VALUES ($1, $2)
ON CONFLICT DO NOTHING
RETURNING group_id
`

type MarkStreakCongratsParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	Month   string      `json:"month"`
}

// Idempotency gate: no row back = another tick (or instance) already sent.
func (q *Queries) MarkStreakCongrats(ctx context.Context, arg MarkStreakCongratsParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, markStreakCongrats, arg.GroupID, arg.Month)
	var group_id pgtype.UUID
	err := row.Scan(&group_id)
	return group_id, err
}

const removeGroupMember = `-- name: RemoveGroupMember :exec
DELETE FROM group_members WHERE group_id = $1 AND user_id = $2
`

type RemoveGroupMemberParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  string      `json:"user_id"`
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error {
	_, err := q.db.Exec(ctx, removeGroupMember, arg.GroupID, arg.UserID)
	return err
}

const setGroupIcon = `-- name: SetGroupIcon :one
UPDATE groups SET icon_url = $2
WHERE id = $1
RETURNING id, owner_id, name, emoji, created_at, icon_url
`

type SetGroupIconParams struct {
	ID      pgtype.UUID `json:"id"`
	IconUrl string      `json:"icon_url"`
}

func (q *Queries) SetGroupIcon(ctx context.Context, arg SetGroupIconParams) (Group, error) {
	row := q.db.QueryRow(ctx, setGroupIcon, arg.ID, arg.IconUrl)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Emoji,
		&i.CreatedAt,
		&i.IconUrl,
	)
	return i, err
}
