// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addEventInvite = `-- name: AddEventInvite :exec

INSERT INTO event_invites (event_id, user_id, inviter_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddEventInviteParams struct {
	EventID   pgtype.UUID `json:"event_id"`
	UserID    string      `json:"user_id"`
	InviterID string      `json:"inviter_id"`
}

// ========================= event invites ==========================
func (q *Queries) AddEventInvite(ctx context.Context, arg AddEventInviteParams) error {
	_, err := q.db.Exec(ctx, addEventInvite, arg.EventID, arg.UserID, arg.InviterID)
	return err
}

const countPendingIncoming = `-- name: CountPendingIncoming :one
SELECT count(*)::int FROM friendships WHERE addressee_id = $1 AND status = 'pending'
`

func (q *Queries) CountPendingIncoming(ctx context.Context, addresseeID string) (int32, error) {
	row := q.db.QueryRow(ctx, countPendingIncoming, addresseeID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countUnseenInvites = `-- name: CountUnseenInvites :one
SELECT count(*)::int FROM event_invites ei
WHERE ei.user_id = $1 AND NOT ei.seen
  AND EXISTS (SELECT 1 FROM events e WHERE e.id = ei.event_id AND e.status <> 'cancelled' AND e.host_id <> $1)
  AND NOT EXISTS (SELECT 1 FROM event_attendees a WHERE a.event_id = ei.event_id AND a.user_id = $1)
  AND NOT EXISTS (SELECT 1 FROM event_cohosts ch WHERE ch.event_id = ei.event_id AND ch.user_id = $1)
`

// Only count invites that still have a clickable tile the user can open to clear
// them — the same set ListEventsInvited surfaces (active event, not your own, not
// one you've already responded to or cohost). Otherwise a cancelled event, a
// self-invite, or an already-RSVP'd invite leaves a badge with no way to dismiss
// it. Responding (RSVP) or opening the event both clear it.
func (q *Queries) CountUnseenInvites(ctx context.Context, userID string) (int32, error) {
	row := q.db.QueryRow(ctx, countUnseenInvites, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const listEventInvites = `-- name: ListEventInvites :many
SELECT i.user_id, i.inviter_id, p.display_name
FROM event_invites i
LEFT JOIN profiles p ON p.user_id = i.user_id
WHERE i.event_id = $1
ORDER BY i.created_at
`

type ListEventInvitesRow struct {
	UserID      string      `json:"user_id"`
	InviterID   string      `json:"inviter_id"`
	DisplayName pgtype.Text `json:"display_name"`
}

func (q *Queries) ListEventInvites(ctx context.Context, eventID pgtype.UUID) ([]ListEventInvitesRow, error) {
	rows, err := q.db.Query(ctx, listEventInvites, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventInvitesRow{}
	for rows.Next() {
		var i ListEventInvitesRow
		if err := rows.Scan(&i.UserID, &i.InviterID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsInvited = `-- name: ListEventsInvited :many
SELECT e.id, e.host_id, e.title, e.event_type, e.description,
       e.location_mode, e.location_address, e.scheduling_mode, e.starts_at, e.status, e.created_at, e.comments_enabled, e.group_id, e.series_id, e.recurrence, e.reminder_sent, e.visibility, e.topic, e.city, e.custom_emoji, e.custom_label, e.general_scope, e.photo_url, e.theme, e.timezone, e.ends_at, e.poll_deadline, e.poll_ready_sent, e.vote_reminder_sent, e.quorum_sent
FROM events e
JOIN event_invites i ON i.event_id = e.id
WHERE i.user_id = $1 AND e.status <> 'cancelled' AND e.host_id <> $1
  AND NOT EXISTS (SELECT 1 FROM event_attendees a WHERE a.event_id = e.id AND a.user_id = $1)
  AND NOT EXISTS (SELECT 1 FROM event_cohosts ch WHERE ch.event_id = e.id AND ch.user_id = $1)
ORDER BY e.created_at DESC
`

func (q *Queries) ListEventsInvited(ctx context.Context, userID string) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsInvited, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Title,
			&i.EventType,
			&i.Description,
			&i.LocationMode,
			&i.LocationAddress,
			&i.SchedulingMode,
			&i.StartsAt,
			&i.Status,
			&i.CreatedAt,
			&i.CommentsEnabled,
			&i.GroupID,
			&i.SeriesID,
			&i.Recurrence,
			&i.ReminderSent,
			&i.Visibility,
			&i.Topic,
			&i.City,
			&i.CustomEmoji,
			&i.CustomLabel,
			&i.GeneralScope,
			&i.PhotoUrl,
			&i.Theme,
			&i.Timezone,
			&i.EndsAt,
			&i.PollDeadline,
			&i.PollReadySent,
			&i.VoteReminderSent,
			&i.QuorumSent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnseenInviteEventIDs = `-- name: ListUnseenInviteEventIDs :many
SELECT ei.event_id FROM event_invites ei
WHERE ei.user_id = $1 AND NOT ei.seen
  AND EXISTS (SELECT 1 FROM events e WHERE e.id = ei.event_id AND e.status <> 'cancelled' AND e.host_id <> $1)
  AND NOT EXISTS (SELECT 1 FROM event_attendees a WHERE a.event_id = ei.event_id AND a.user_id = $1)
  AND NOT EXISTS (SELECT 1 FROM event_cohosts ch WHERE ch.event_id = ei.event_id AND ch.user_id = $1)
`

// Same filter as CountUnseenInvites so the per-event "new" dots match the badge.
func (q *Queries) ListUnseenInviteEventIDs(ctx context.Context, userID string) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listUnseenInviteEventIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var event_id pgtype.UUID
		if err := rows.Scan(&event_id); err != nil {
			return nil, err
		}
		items = append(items, event_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOneInviteSeen = `-- name: MarkOneInviteSeen :exec
UPDATE event_invites SET seen = true WHERE event_id = $1 AND user_id = $2
`

type MarkOneInviteSeenParams struct {
	EventID pgtype.UUID `json:"event_id"`
	UserID  string      `json:"user_id"`
}

func (q *Queries) MarkOneInviteSeen(ctx context.Context, arg MarkOneInviteSeenParams) error {
	_, err := q.db.Exec(ctx, markOneInviteSeen, arg.EventID, arg.UserID)
	return err
}
