// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AvailabilityDay struct {
	UserID  string      `json:"user_id"`
	Day     pgtype.Date `json:"day"`
	Daypart string      `json:"daypart"`
	Status  string      `json:"status"`
}

type AvailabilitySlot struct {
	UserID    string `json:"user_id"`
	Weekday   int16  `json:"weekday"`
	PartOfDay string `json:"part_of_day"`
	Status    string `json:"status"`
}

type CalendarConnection struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       string             `json:"user_id"`
	Provider     string             `json:"provider"`
	AccountLabel string             `json:"account_label"`
	AccessToken  string             `json:"access_token"`
	RefreshToken string             `json:"refresh_token"`
	TokenExpiry  pgtype.Timestamptz `json:"token_expiry"`
	IcalUrl      string             `json:"ical_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type CustomEventType struct {
	UserID    string             `json:"user_id"`
	Label     string             `json:"label"`
	Emoji     string             `json:"emoji"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Event struct {
	ID              pgtype.UUID        `json:"id"`
	HostID          string             `json:"host_id"`
	Title           string             `json:"title"`
	EventType       string             `json:"event_type"`
	Description     string             `json:"description"`
	LocationMode    string             `json:"location_mode"`
	LocationAddress string             `json:"location_address"`
	SchedulingMode  string             `json:"scheduling_mode"`
	StartsAt        pgtype.Timestamptz `json:"starts_at"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CommentsEnabled bool               `json:"comments_enabled"`
	GroupID         pgtype.UUID        `json:"group_id"`
	SeriesID        pgtype.UUID        `json:"series_id"`
	Recurrence      string             `json:"recurrence"`
	ReminderSent    bool               `json:"reminder_sent"`
	Visibility      string             `json:"visibility"`
	Topic           string             `json:"topic"`
	City            string             `json:"city"`
	CustomEmoji     string             `json:"custom_emoji"`
	CustomLabel     string             `json:"custom_label"`
}

type EventAttendee struct {
	ID        pgtype.UUID        `json:"id"`
	EventID   pgtype.UUID        `json:"event_id"`
	UserID    string             `json:"user_id"`
	Rsvp      string             `json:"rsvp"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type EventCohost struct {
	EventID   pgtype.UUID        `json:"event_id"`
	UserID    string             `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type EventComment struct {
	ID        pgtype.UUID        `json:"id"`
	EventID   pgtype.UUID        `json:"event_id"`
	UserID    string             `json:"user_id"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type EventGeneralVote struct {
	ID        pgtype.UUID `json:"id"`
	EventID   pgtype.UUID `json:"event_id"`
	UserID    string      `json:"user_id"`
	Dimension string      `json:"dimension"`
	Value     string      `json:"value"`
}

type EventInvite struct {
	EventID   pgtype.UUID        `json:"event_id"`
	UserID    string             `json:"user_id"`
	InviterID string             `json:"inviter_id"`
	Seen      bool               `json:"seen"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type EventPreferenceAnswer struct {
	ID          pgtype.UUID `json:"id"`
	EventID     pgtype.UUID `json:"event_id"`
	UserID      string      `json:"user_id"`
	QuestionKey string      `json:"question_key"`
	Answer      string      `json:"answer"`
}

type EventTimeOption struct {
	ID       pgtype.UUID        `json:"id"`
	EventID  pgtype.UUID        `json:"event_id"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
}

type EventTimeVote struct {
	ID       pgtype.UUID `json:"id"`
	OptionID pgtype.UUID `json:"option_id"`
	UserID   string      `json:"user_id"`
	Response string      `json:"response"`
}

type Follow struct {
	UserID    string             `json:"user_id"`
	Kind      string             `json:"kind"`
	Value     string             `json:"value"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Friendship struct {
	ID          pgtype.UUID        `json:"id"`
	RequesterID string             `json:"requester_id"`
	AddresseeID string             `json:"addressee_id"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Group struct {
	ID        pgtype.UUID        `json:"id"`
	OwnerID   string             `json:"owner_id"`
	Name      string             `json:"name"`
	Emoji     string             `json:"emoji"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	IconUrl   string             `json:"icon_url"`
}

type GroupMember struct {
	GroupID   pgtype.UUID        `json:"group_id"`
	UserID    string             `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Note struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    string             `json:"user_id"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Profile struct {
	UserID      string             `json:"user_id"`
	DisplayName string             `json:"display_name"`
	Handle      string             `json:"handle"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	AvatarUrl   string             `json:"avatar_url"`
	Email       string             `json:"email"`
}
