// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AvailabilityDay struct {
	UserID  string      `json:"user_id"`
	Day     pgtype.Date `json:"day"`
	Daypart string      `json:"daypart"`
	Status  string      `json:"status"`
}

type AvailabilitySlot struct {
	UserID    string `json:"user_id"`
	Weekday   int16  `json:"weekday"`
	PartOfDay string `json:"part_of_day"`
	Status    string `json:"status"`
}

type CalendarConnection struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       string             `json:"user_id"`
	Provider     string             `json:"provider"`
	AccountLabel string             `json:"account_label"`
	AccessToken  string             `json:"access_token"`
	RefreshToken string             `json:"refresh_token"`
	TokenExpiry  pgtype.Timestamptz `json:"token_expiry"`
	IcalUrl      string             `json:"ical_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type CronRunClaim struct {
	Job       string             `json:"job"`
	RunDay    pgtype.Date        `json:"run_day"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CustomEventType struct {
	UserID    string             `json:"user_id"`
	Label     string             `json:"label"`
	Emoji     string             `json:"emoji"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Event struct {
	ID               pgtype.UUID        `json:"id"`
	HostID           string             `json:"host_id"`
	Title            string             `json:"title"`
	EventType        string             `json:"event_type"`
	Description      string             `json:"description"`
	LocationMode     string             `json:"location_mode"`
	LocationAddress  string             `json:"location_address"`
	SchedulingMode   string             `json:"scheduling_mode"`
	StartsAt         pgtype.Timestamptz `json:"starts_at"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	CommentsEnabled  bool               `json:"comments_enabled"`
	GroupID          pgtype.UUID        `json:"group_id"`
	SeriesID         pgtype.UUID        `json:"series_id"`
	Recurrence       string             `json:"recurrence"`
	ReminderSent     bool               `json:"reminder_sent"`
	Visibility       string             `json:"visibility"`
	Topic            string             `json:"topic"`
	City             string             `json:"city"`
	CustomEmoji      string             `json:"custom_emoji"`
	CustomLabel      string             `json:"custom_label"`
	GeneralScope     string             `json:"general_scope"`
	PhotoUrl         string             `json:"photo_url"`
	Theme            string             `json:"theme"`
	Timezone         string             `json:"timezone"`
	EndsAt           pgtype.Timestamptz `json:"ends_at"`
	PollDeadline     pgtype.Timestamptz `json:"poll_deadline"`
	PollReadySent    bool               `json:"poll_ready_sent"`
	VoteReminderSent bool               `json:"vote_reminder_sent"`
	QuorumSent       bool               `json:"quorum_sent"`
	Capacity         int32              `json:"capacity"`
}

type EventAttendee struct {
	ID        pgtype.UUID        `json:"id"`
	EventID   pgtype.UUID        `json:"event_id"`
	UserID    string             `json:"user_id"`
	Rsvp      string             `json:"rsvp"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Anonymous bool               `json:"anonymous"`
}

type EventCohost struct {
	EventID   pgtype.UUID        `json:"event_id"`
	UserID    string             `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type EventComment struct {
	ID        pgtype.UUID        `json:"id"`
	EventID   pgtype.UUID        `json:"event_id"`
	UserID    string             `json:"user_id"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	GifUrl    string             `json:"gif_url"`
}

type EventGeneralVote struct {
	ID        pgtype.UUID `json:"id"`
	EventID   pgtype.UUID `json:"event_id"`
	UserID    string      `json:"user_id"`
	Dimension string      `json:"dimension"`
	Value     string      `json:"value"`
}

type EventInvite struct {
	EventID   pgtype.UUID        `json:"event_id"`
	UserID    string             `json:"user_id"`
	InviterID string             `json:"inviter_id"`
	Seen      bool               `json:"seen"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type EventMute struct {
	EventID   pgtype.UUID        `json:"event_id"`
	UserID    string             `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type EventNudge struct {
	EventID  pgtype.UUID        `json:"event_id"`
	NudgedAt pgtype.Timestamptz `json:"nudged_at"`
}

type EventPollDay struct {
	EventID pgtype.UUID `json:"event_id"`
	Day     pgtype.Date `json:"day"`
}

type EventPollTimeGrid struct {
	EventID  pgtype.UUID `json:"event_id"`
	StartMin int32       `json:"start_min"`
	EndMin   int32       `json:"end_min"`
	SlotMin  int32       `json:"slot_min"`
}

type EventPreferenceAnswer struct {
	ID          pgtype.UUID `json:"id"`
	EventID     pgtype.UUID `json:"event_id"`
	UserID      string      `json:"user_id"`
	QuestionKey string      `json:"question_key"`
	Answer      string      `json:"answer"`
}

type EventRecap struct {
	EventID pgtype.UUID        `json:"event_id"`
	SentAt  pgtype.Timestamptz `json:"sent_at"`
}

type EventTimeOption struct {
	ID       pgtype.UUID        `json:"id"`
	EventID  pgtype.UUID        `json:"event_id"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
}

type EventTimeVote struct {
	ID       pgtype.UUID `json:"id"`
	OptionID pgtype.UUID `json:"option_id"`
	UserID   string      `json:"user_id"`
	Response string      `json:"response"`
}

type Follow struct {
	UserID    string             `json:"user_id"`
	Kind      string             `json:"kind"`
	Value     string             `json:"value"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Friendship struct {
	ID          pgtype.UUID        `json:"id"`
	RequesterID string             `json:"requester_id"`
	AddresseeID string             `json:"addressee_id"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Group struct {
	ID          pgtype.UUID        `json:"id"`
	OwnerID     string             `json:"owner_id"`
	Name        string             `json:"name"`
	Emoji       string             `json:"emoji"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	IconUrl     string             `json:"icon_url"`
	Description string             `json:"description"`
}

type GroupMember struct {
	GroupID   pgtype.UUID        `json:"group_id"`
	UserID    string             `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Role      string             `json:"role"`
}

type GroupStreakCongrat struct {
	GroupID pgtype.UUID        `json:"group_id"`
	Month   string             `json:"month"`
	SentAt  pgtype.Timestamptz `json:"sent_at"`
}

type Note struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    string             `json:"user_id"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type NotificationQueue struct {
	ID          pgtype.UUID        `json:"id"`
	RecipientID string             `json:"recipient_id"`
	EventID     pgtype.UUID        `json:"event_id"`
	Kind        string             `json:"kind"`
	ActorID     string             `json:"actor_id"`
	ActorName   string             `json:"actor_name"`
	Body        string             `json:"body"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Profile struct {
	UserID      string             `json:"user_id"`
	DisplayName string             `json:"display_name"`
	Handle      string             `json:"handle"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	AvatarUrl   string             `json:"avatar_url"`
	Email       string             `json:"email"`
}
