// Code generated by sqlc. DO NOT EDIT.
package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Note struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    string             `json:"user_id"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
