// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mute.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const isEventMuted = `-- name: IsEventMuted :one
SELECT EXISTS (
    SELECT 1 FROM event_mutes WHERE event_id = $1 AND user_id = $2
) AS muted
`

type IsEventMutedParams struct {
	EventID pgtype.UUID `json:"event_id"`
	UserID  string      `json:"user_id"`
}

func (q *Queries) IsEventMuted(ctx context.Context, arg IsEventMutedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isEventMuted, arg.EventID, arg.UserID)
	var muted bool
	err := row.Scan(&muted)
	return muted, err
}

const listGoingAttendeeContacts = `-- name: ListGoingAttendeeContacts :many
SELECT a.user_id, p.email
FROM event_attendees a
JOIN profiles p ON p.user_id = a.user_id
WHERE a.event_id = $1 AND a.rsvp = 'going' AND p.email <> ''
  AND NOT EXISTS (SELECT 1 FROM event_mutes m WHERE m.event_id = a.event_id AND m.user_id = a.user_id)
`

type ListGoingAttendeeContactsRow struct {
	UserID string `json:"user_id"`
	Email  string `json:"email"`
}

// (user_id, email) for going attendees with an email who have NOT muted this
// event — the recipients of finalize/reminder/cancel mail. Returning the user_id
// lets the sender mint a per-recipient one-click unsubscribe token.
func (q *Queries) ListGoingAttendeeContacts(ctx context.Context, eventID pgtype.UUID) ([]ListGoingAttendeeContactsRow, error) {
	rows, err := q.db.Query(ctx, listGoingAttendeeContacts, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGoingAttendeeContactsRow{}
	for rows.Next() {
		var i ListGoingAttendeeContactsRow
		if err := rows.Scan(&i.UserID, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const muteEvent = `-- name: MuteEvent :exec

INSERT INTO event_mutes (event_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type MuteEventParams struct {
	EventID pgtype.UUID `json:"event_id"`
	UserID  string      `json:"user_id"`
}

// ==================== notification mutes ==========================
func (q *Queries) MuteEvent(ctx context.Context, arg MuteEventParams) error {
	_, err := q.db.Exec(ctx, muteEvent, arg.EventID, arg.UserID)
	return err
}

const unmuteEvent = `-- name: UnmuteEvent :exec
DELETE FROM event_mutes WHERE event_id = $1 AND user_id = $2
`

type UnmuteEventParams struct {
	EventID pgtype.UUID `json:"event_id"`
	UserID  string      `json:"user_id"`
}

func (q *Queries) UnmuteEvent(ctx context.Context, arg UnmuteEventParams) error {
	_, err := q.db.Exec(ctx, unmuteEvent, arg.EventID, arg.UserID)
	return err
}
