// Code generated by sqlc. DO NOT EDIT.
// source: notes.sql
package db

import (
	"context"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (user_id, body)
VALUES ($1, $2)
RETURNING id, user_id, body, created_at
`

type CreateNoteParams struct {
	UserID string `json:"user_id"`
	Body   string `json:"body"`
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, createNote, arg.UserID, arg.Body)
	var i Note
	err := row.Scan(&i.ID, &i.UserID, &i.Body, &i.CreatedAt)
	return i, err
}

const listNotes = `-- name: ListNotes :many
SELECT id, user_id, body, created_at
FROM notes
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 100
`

func (q *Queries) ListNotes(ctx context.Context, userID string) ([]Note, error) {
	rows, err := q.db.Query(ctx, listNotes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(&i.ID, &i.UserID, &i.Body, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
