// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifq.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const drainDueNotifications = `-- name: DrainDueNotifications :many
DELETE FROM notification_queue
WHERE created_at < now() - make_interval(mins => $1::int)
RETURNING recipient_id, event_id, kind, actor_id, actor_name, body, created_at
`

type DrainDueNotificationsRow struct {
	RecipientID string             `json:"recipient_id"`
	EventID     pgtype.UUID        `json:"event_id"`
	Kind        string             `json:"kind"`
	ActorID     string             `json:"actor_id"`
	ActorName   string             `json:"actor_name"`
	Body        string             `json:"body"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// Atomically claim every item older than the digest window. DELETE..RETURNING
// hands each row to exactly one caller, so overlapping flushers (Cloud Run can
// run 2 instances) can't double-send.
func (q *Queries) DrainDueNotifications(ctx context.Context, dollar_1 int32) ([]DrainDueNotificationsRow, error) {
	rows, err := q.db.Query(ctx, drainDueNotifications, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DrainDueNotificationsRow{}
	for rows.Next() {
		var i DrainDueNotificationsRow
		if err := rows.Scan(
			&i.RecipientID,
			&i.EventID,
			&i.Kind,
			&i.ActorID,
			&i.ActorName,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueNotification = `-- name: EnqueueNotification :exec

INSERT INTO notification_queue (recipient_id, event_id, kind, actor_id, actor_name, body)
VALUES ($1, $2, $3, $4, $5, $6)
`

type EnqueueNotificationParams struct {
	RecipientID string      `json:"recipient_id"`
	EventID     pgtype.UUID `json:"event_id"`
	Kind        string      `json:"kind"`
	ActorID     string      `json:"actor_id"`
	ActorName   string      `json:"actor_name"`
	Body        string      `json:"body"`
}

// ================== activity-notification queue ===================
func (q *Queries) EnqueueNotification(ctx context.Context, arg EnqueueNotificationParams) error {
	_, err := q.db.Exec(ctx, enqueueNotification,
		arg.RecipientID,
		arg.EventID,
		arg.Kind,
		arg.ActorID,
		arg.ActorName,
		arg.Body,
	)
	return err
}
