// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nudge.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getNudgedAt = `-- name: GetNudgedAt :one

SELECT nudged_at FROM event_nudges WHERE event_id = $1
`

// ====================== host nudge ================================
func (q *Queries) GetNudgedAt(ctx context.Context, eventID pgtype.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getNudgedAt, eventID)
	var nudged_at pgtype.Timestamptz
	err := row.Scan(&nudged_at)
	return nudged_at, err
}

const listInvitedNonResponderContacts = `-- name: ListInvitedNonResponderContacts :many
SELECT i.user_id, p.email
FROM event_invites i
JOIN profiles p ON p.user_id = i.user_id
WHERE i.event_id = $1 AND p.email <> ''
  AND NOT EXISTS (SELECT 1 FROM event_attendees a WHERE a.event_id = i.event_id AND a.user_id = i.user_id)
  AND NOT EXISTS (SELECT 1 FROM event_mutes m WHERE m.event_id = i.event_id AND m.user_id = i.user_id)
`

type ListInvitedNonResponderContactsRow struct {
	UserID string `json:"user_id"`
	Email  string `json:"email"`
}

// (user_id, email) for invited people who have NOT RSVP'd at all — the Nudge
// audience. Requires an email, skips anyone who muted this event's mail.
func (q *Queries) ListInvitedNonResponderContacts(ctx context.Context, eventID pgtype.UUID) ([]ListInvitedNonResponderContactsRow, error) {
	rows, err := q.db.Query(ctx, listInvitedNonResponderContacts, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvitedNonResponderContactsRow{}
	for rows.Next() {
		var i ListInvitedNonResponderContactsRow
		if err := rows.Scan(&i.UserID, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNudged = `-- name: MarkNudged :exec
INSERT INTO event_nudges (event_id, nudged_at)
VALUES ($1, now())
ON CONFLICT (event_id) DO UPDATE SET nudged_at = now()
`

func (q *Queries) MarkNudged(ctx context.Context, eventID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markNudged, eventID)
	return err
}
