// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: performers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPerformer = `-- name: AddPerformer :exec

INSERT INTO event_performers (event_id, user_id, added_by)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddPerformerParams struct {
	EventID pgtype.UUID `json:"event_id"`
	UserID  string      `json:"user_id"`
	AddedBy string      `json:"added_by"`
}

// performers.sql - V7 of the venue-pages playbook (docs/product/VENUE-PAGES.md):
// performers on events. Mirrors event_cohosts (comments.sql) - real users added
// by handle, PK(event_id, user_id) - with one addition: status, because a
// performer's own consent gates whether the event surfaces to THEIR followers
// (display on the event page is immediate; feed/digest distribution is not).
func (q *Queries) AddPerformer(ctx context.Context, arg AddPerformerParams) error {
	_, err := q.db.Exec(ctx, addPerformer, arg.EventID, arg.UserID, arg.AddedBy)
	return err
}

const confirmPerformer = `-- name: ConfirmPerformer :one
UPDATE event_performers SET status = 'confirmed'
WHERE event_id = $1 AND user_id = $2 AND status = 'pending'
RETURNING event_id
`

type ConfirmPerformerParams struct {
	EventID pgtype.UUID `json:"event_id"`
	UserID  string      `json:"user_id"`
}

// Atomic once-gate mirroring ClaimEventReminder: a row back means this call
// flipped pending -> confirmed (the performer's consent - see the migration
// comment). Idempotent: a second tap on the same email link no-ops (no row).
func (q *Queries) ConfirmPerformer(ctx context.Context, arg ConfirmPerformerParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, confirmPerformer, arg.EventID, arg.UserID)
	var event_id pgtype.UUID
	err := row.Scan(&event_id)
	return event_id, err
}

const getPerformer = `-- name: GetPerformer :one
SELECT event_id, user_id, status, added_by, created_at
FROM event_performers
WHERE event_id = $1 AND user_id = $2
`

type GetPerformerParams struct {
	EventID pgtype.UUID `json:"event_id"`
	UserID  string      `json:"user_id"`
}

func (q *Queries) GetPerformer(ctx context.Context, arg GetPerformerParams) (EventPerformer, error) {
	row := q.db.QueryRow(ctx, getPerformer, arg.EventID, arg.UserID)
	var i EventPerformer
	err := row.Scan(
		&i.EventID,
		&i.UserID,
		&i.Status,
		&i.AddedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listPerformers = `-- name: ListPerformers :many
SELECT ep.event_id, ep.user_id, ep.status, ep.added_by, ep.created_at,
       p.display_name, p.handle, p.avatar_url
FROM event_performers ep
LEFT JOIN profiles p ON p.user_id = ep.user_id
WHERE ep.event_id = $1
ORDER BY ep.created_at
`

type ListPerformersRow struct {
	EventID     pgtype.UUID        `json:"event_id"`
	UserID      string             `json:"user_id"`
	Status      string             `json:"status"`
	AddedBy     string             `json:"added_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	DisplayName pgtype.Text        `json:"display_name"`
	Handle      pgtype.Text        `json:"handle"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) ListPerformers(ctx context.Context, eventID pgtype.UUID) ([]ListPerformersRow, error) {
	rows, err := q.db.Query(ctx, listPerformers, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPerformersRow{}
	for rows.Next() {
		var i ListPerformersRow
		if err := rows.Scan(
			&i.EventID,
			&i.UserID,
			&i.Status,
			&i.AddedBy,
			&i.CreatedAt,
			&i.DisplayName,
			&i.Handle,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePerformer = `-- name: RemovePerformer :exec
DELETE FROM event_performers WHERE event_id = $1 AND user_id = $2
`

type RemovePerformerParams struct {
	EventID pgtype.UUID `json:"event_id"`
	UserID  string      `json:"user_id"`
}

func (q *Queries) RemovePerformer(ctx context.Context, arg RemovePerformerParams) error {
	_, err := q.db.Exec(ctx, removePerformer, arg.EventID, arg.UserID)
	return err
}
