// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recap.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimEventRecap = `-- name: ClaimEventRecap :one
INSERT INTO event_recaps (event_id) VALUES ($1)
ON CONFLICT DO NOTHING
RETURNING event_id
`

// Atomic once-gate (multi-instance + retry safe): a row back means THIS call
// inserted the recap marker and owns the send; no row = already recapped, skip.
func (q *Queries) ClaimEventRecap(ctx context.Context, eventID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, claimEventRecap, eventID)
	var event_id pgtype.UUID
	err := row.Scan(&event_id)
	return event_id, err
}

const listEventsNeedingRecap = `-- name: ListEventsNeedingRecap :many

SELECT id, host_id, title, event_type, description,
       location_mode, location_address, scheduling_mode, starts_at, status, created_at, comments_enabled, group_id, series_id, recurrence, reminder_sent, visibility, topic, city, custom_emoji, custom_label, general_scope, photo_url, theme, timezone, ends_at, poll_deadline, poll_ready_sent, vote_reminder_sent, quorum_sent, capacity
FROM events
WHERE status = 'scheduled'
  AND (starts_at AT TIME ZONE 'America/Los_Angeles')::date
      = ((now() AT TIME ZONE 'America/Los_Angeles')::date - 1)
  AND NOT EXISTS (SELECT 1 FROM event_recaps rc WHERE rc.event_id = events.id)
`

// ===================== post-event recap ===========================
// Events that happened on the PREVIOUS Pacific calendar day and haven't been
// recapped — the day-after "how was it? plan the next one" email, sent by the
// same daily 2pm-Pacific cron as reminders.
func (q *Queries) ListEventsNeedingRecap(ctx context.Context) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsNeedingRecap)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Title,
			&i.EventType,
			&i.Description,
			&i.LocationMode,
			&i.LocationAddress,
			&i.SchedulingMode,
			&i.StartsAt,
			&i.Status,
			&i.CreatedAt,
			&i.CommentsEnabled,
			&i.GroupID,
			&i.SeriesID,
			&i.Recurrence,
			&i.ReminderSent,
			&i.Visibility,
			&i.Topic,
			&i.City,
			&i.CustomEmoji,
			&i.CustomLabel,
			&i.GeneralScope,
			&i.PhotoUrl,
			&i.Theme,
			&i.Timezone,
			&i.EndsAt,
			&i.PollDeadline,
			&i.PollReadySent,
			&i.VoteReminderSent,
			&i.QuorumSent,
			&i.Capacity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
