// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recap.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listEventsNeedingRecap = `-- name: ListEventsNeedingRecap :many

SELECT id, host_id, title, event_type, description,
       location_mode, location_address, scheduling_mode, starts_at, status, created_at, comments_enabled, group_id, series_id, recurrence, reminder_sent, visibility, topic, city, custom_emoji, custom_label, general_scope, photo_url, theme, timezone
FROM events
WHERE status = 'scheduled'
  AND (starts_at AT TIME ZONE 'America/Los_Angeles')::date
      = ((now() AT TIME ZONE 'America/Los_Angeles')::date - 1)
  AND NOT EXISTS (SELECT 1 FROM event_recaps rc WHERE rc.event_id = events.id)
`

// ===================== post-event recap ===========================
// Events that happened on the PREVIOUS Pacific calendar day and haven't been
// recapped — the day-after "how was it? plan the next one" email, sent by the
// same daily 2pm-Pacific cron as reminders.
func (q *Queries) ListEventsNeedingRecap(ctx context.Context) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsNeedingRecap)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Title,
			&i.EventType,
			&i.Description,
			&i.LocationMode,
			&i.LocationAddress,
			&i.SchedulingMode,
			&i.StartsAt,
			&i.Status,
			&i.CreatedAt,
			&i.CommentsEnabled,
			&i.GroupID,
			&i.SeriesID,
			&i.Recurrence,
			&i.ReminderSent,
			&i.Visibility,
			&i.Topic,
			&i.City,
			&i.CustomEmoji,
			&i.CustomLabel,
			&i.GeneralScope,
			&i.PhotoUrl,
			&i.Theme,
			&i.Timezone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRecapSent = `-- name: MarkRecapSent :exec
INSERT INTO event_recaps (event_id) VALUES ($1) ON CONFLICT DO NOTHING
`

func (q *Queries) MarkRecapSent(ctx context.Context, eventID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markRecapSent, eventID)
	return err
}
