// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduler.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptFriendRequest = `-- name: AcceptFriendRequest :one
UPDATE friendships
SET status = 'accepted'
WHERE id = $1 AND addressee_id = $2 AND status = 'pending'
RETURNING id, requester_id, addressee_id, status, created_at
`

type AcceptFriendRequestParams struct {
	ID          pgtype.UUID `json:"id"`
	AddresseeID string      `json:"addressee_id"`
}

func (q *Queries) AcceptFriendRequest(ctx context.Context, arg AcceptFriendRequestParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, acceptFriendRequest, arg.ID, arg.AddresseeID)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const addAvailabilityDay = `-- name: AddAvailabilityDay :exec
INSERT INTO availability_days (user_id, day, daypart, status)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type AddAvailabilityDayParams struct {
	UserID  string      `json:"user_id"`
	Day     pgtype.Date `json:"day"`
	Daypart string      `json:"daypart"`
	Status  string      `json:"status"`
}

func (q *Queries) AddAvailabilityDay(ctx context.Context, arg AddAvailabilityDayParams) error {
	_, err := q.db.Exec(ctx, addAvailabilityDay,
		arg.UserID,
		arg.Day,
		arg.Daypart,
		arg.Status,
	)
	return err
}

const addAvailabilitySlot = `-- name: AddAvailabilitySlot :exec
INSERT INTO availability_slots (user_id, weekday, part_of_day, status)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type AddAvailabilitySlotParams struct {
	UserID    string `json:"user_id"`
	Weekday   int16  `json:"weekday"`
	PartOfDay string `json:"part_of_day"`
	Status    string `json:"status"`
}

func (q *Queries) AddAvailabilitySlot(ctx context.Context, arg AddAvailabilitySlotParams) error {
	_, err := q.db.Exec(ctx, addAvailabilitySlot,
		arg.UserID,
		arg.Weekday,
		arg.PartOfDay,
		arg.Status,
	)
	return err
}

const addGeneralVote = `-- name: AddGeneralVote :exec
INSERT INTO event_general_votes (event_id, user_id, dimension, value)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type AddGeneralVoteParams struct {
	EventID   pgtype.UUID `json:"event_id"`
	UserID    string      `json:"user_id"`
	Dimension string      `json:"dimension"`
	Value     string      `json:"value"`
}

func (q *Queries) AddGeneralVote(ctx context.Context, arg AddGeneralVoteParams) error {
	_, err := q.db.Exec(ctx, addGeneralVote,
		arg.EventID,
		arg.UserID,
		arg.Dimension,
		arg.Value,
	)
	return err
}

const addTimeOption = `-- name: AddTimeOption :one

INSERT INTO event_time_options (event_id, starts_at)
VALUES ($1, $2)
RETURNING id, event_id, starts_at
`

type AddTimeOptionParams struct {
	EventID  pgtype.UUID        `json:"event_id"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
}

// ====================== event time options ========================
func (q *Queries) AddTimeOption(ctx context.Context, arg AddTimeOptionParams) (EventTimeOption, error) {
	row := q.db.QueryRow(ctx, addTimeOption, arg.EventID, arg.StartsAt)
	var i EventTimeOption
	err := row.Scan(&i.ID, &i.EventID, &i.StartsAt)
	return i, err
}

const areFriends = `-- name: AreFriends :one
SELECT EXISTS (
    SELECT 1 FROM friendships
    WHERE status = 'accepted'
      AND ((requester_id = $1 AND addressee_id = $2)
        OR (requester_id = $2 AND addressee_id = $1))
) AS are_friends
`

type AreFriendsParams struct {
	RequesterID string `json:"requester_id"`
	AddresseeID string `json:"addressee_id"`
}

func (q *Queries) AreFriends(ctx context.Context, arg AreFriendsParams) (bool, error) {
	row := q.db.QueryRow(ctx, areFriends, arg.RequesterID, arg.AddresseeID)
	var are_friends bool
	err := row.Scan(&are_friends)
	return are_friends, err
}

const cancelEvent = `-- name: CancelEvent :one
UPDATE events SET status = 'cancelled'
WHERE id = $1
RETURNING id, host_id, title, event_type, description,
          location_mode, location_address, scheduling_mode, starts_at, status, created_at, comments_enabled, group_id, series_id, recurrence, reminder_sent, visibility, topic, city, custom_emoji, custom_label, general_scope
`

func (q *Queries) CancelEvent(ctx context.Context, id pgtype.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, cancelEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Title,
		&i.EventType,
		&i.Description,
		&i.LocationMode,
		&i.LocationAddress,
		&i.SchedulingMode,
		&i.StartsAt,
		&i.Status,
		&i.CreatedAt,
		&i.CommentsEnabled,
		&i.GroupID,
		&i.SeriesID,
		&i.Recurrence,
		&i.ReminderSent,
		&i.Visibility,
		&i.Topic,
		&i.City,
		&i.CustomEmoji,
		&i.CustomLabel,
		&i.GeneralScope,
	)
	return i, err
}

const cancelSeries = `-- name: CancelSeries :exec
UPDATE events SET status = 'cancelled' WHERE series_id = $1
`

func (q *Queries) CancelSeries(ctx context.Context, seriesID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, cancelSeries, seriesID)
	return err
}

const clearAvailability = `-- name: ClearAvailability :exec
DELETE FROM availability_slots
WHERE user_id = $1
`

func (q *Queries) ClearAvailability(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, clearAvailability, userID)
	return err
}

const clearAvailabilityDays = `-- name: ClearAvailabilityDays :exec
DELETE FROM availability_days
WHERE user_id = $1
`

func (q *Queries) ClearAvailabilityDays(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, clearAvailabilityDays, userID)
	return err
}

const clearGeneralVotes = `-- name: ClearGeneralVotes :exec

DELETE FROM event_general_votes
WHERE event_id = $1 AND user_id = $2
`

type ClearGeneralVotesParams struct {
	EventID pgtype.UUID `json:"event_id"`
	UserID  string      `json:"user_id"`
}

// ====================== general poll votes ========================
func (q *Queries) ClearGeneralVotes(ctx context.Context, arg ClearGeneralVotesParams) error {
	_, err := q.db.Exec(ctx, clearGeneralVotes, arg.EventID, arg.UserID)
	return err
}

const createEvent = `-- name: CreateEvent :one

INSERT INTO events (
    host_id, title, event_type, description,
    location_mode, location_address, scheduling_mode, starts_at, status, group_id, series_id, recurrence,
    visibility, topic, city, custom_emoji, custom_label, general_scope
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
RETURNING id, host_id, title, event_type, description,
          location_mode, location_address, scheduling_mode, starts_at, status, created_at, comments_enabled, group_id, series_id, recurrence, reminder_sent, visibility, topic, city, custom_emoji, custom_label, general_scope
`

type CreateEventParams struct {
	HostID          string             `json:"host_id"`
	Title           string             `json:"title"`
	EventType       string             `json:"event_type"`
	Description     string             `json:"description"`
	LocationMode    string             `json:"location_mode"`
	LocationAddress string             `json:"location_address"`
	SchedulingMode  string             `json:"scheduling_mode"`
	StartsAt        pgtype.Timestamptz `json:"starts_at"`
	Status          string             `json:"status"`
	GroupID         pgtype.UUID        `json:"group_id"`
	SeriesID        pgtype.UUID        `json:"series_id"`
	Recurrence      string             `json:"recurrence"`
	Visibility      string             `json:"visibility"`
	Topic           string             `json:"topic"`
	City            string             `json:"city"`
	CustomEmoji     string             `json:"custom_emoji"`
	CustomLabel     string             `json:"custom_label"`
	GeneralScope    string             `json:"general_scope"`
}

// =========================== events ===============================
func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.HostID,
		arg.Title,
		arg.EventType,
		arg.Description,
		arg.LocationMode,
		arg.LocationAddress,
		arg.SchedulingMode,
		arg.StartsAt,
		arg.Status,
		arg.GroupID,
		arg.SeriesID,
		arg.Recurrence,
		arg.Visibility,
		arg.Topic,
		arg.City,
		arg.CustomEmoji,
		arg.CustomLabel,
		arg.GeneralScope,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Title,
		&i.EventType,
		&i.Description,
		&i.LocationMode,
		&i.LocationAddress,
		&i.SchedulingMode,
		&i.StartsAt,
		&i.Status,
		&i.CreatedAt,
		&i.CommentsEnabled,
		&i.GroupID,
		&i.SeriesID,
		&i.Recurrence,
		&i.ReminderSent,
		&i.Visibility,
		&i.Topic,
		&i.City,
		&i.CustomEmoji,
		&i.CustomLabel,
		&i.GeneralScope,
	)
	return i, err
}

const createFriendRequest = `-- name: CreateFriendRequest :one

INSERT INTO friendships (requester_id, addressee_id)
VALUES ($1, $2)
ON CONFLICT (requester_id, addressee_id) DO NOTHING
RETURNING id, requester_id, addressee_id, status, created_at
`

type CreateFriendRequestParams struct {
	RequesterID string `json:"requester_id"`
	AddresseeID string `json:"addressee_id"`
}

// ========================= friendships ============================
func (q *Queries) CreateFriendRequest(ctx context.Context, arg CreateFriendRequestParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, createFriendRequest, arg.RequesterID, arg.AddresseeID)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFriendship = `-- name: DeleteFriendship :exec
DELETE FROM friendships WHERE id = $1
`

func (q *Queries) DeleteFriendship(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFriendship, id)
	return err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = $1 AND owner_id = $2
`

type DeleteGroupParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID string      `json:"owner_id"`
}

func (q *Queries) DeleteGroup(ctx context.Context, arg DeleteGroupParams) error {
	_, err := q.db.Exec(ctx, deleteGroup, arg.ID, arg.OwnerID)
	return err
}

const finalizeEvent = `-- name: FinalizeEvent :one
UPDATE events
SET starts_at = $2, status = 'scheduled'
WHERE id = $1
RETURNING id, host_id, title, event_type, description,
          location_mode, location_address, scheduling_mode, starts_at, status, created_at, comments_enabled, group_id, series_id, recurrence, reminder_sent, visibility, topic, city, custom_emoji, custom_label, general_scope
`

type FinalizeEventParams struct {
	ID       pgtype.UUID        `json:"id"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
}

func (q *Queries) FinalizeEvent(ctx context.Context, arg FinalizeEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, finalizeEvent, arg.ID, arg.StartsAt)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Title,
		&i.EventType,
		&i.Description,
		&i.LocationMode,
		&i.LocationAddress,
		&i.SchedulingMode,
		&i.StartsAt,
		&i.Status,
		&i.CreatedAt,
		&i.CommentsEnabled,
		&i.GroupID,
		&i.SeriesID,
		&i.Recurrence,
		&i.ReminderSent,
		&i.Visibility,
		&i.Topic,
		&i.City,
		&i.CustomEmoji,
		&i.CustomLabel,
		&i.GeneralScope,
	)
	return i, err
}

const getAttendee = `-- name: GetAttendee :one
SELECT id, event_id, user_id, rsvp, created_at
FROM event_attendees
WHERE event_id = $1 AND user_id = $2
`

type GetAttendeeParams struct {
	EventID pgtype.UUID `json:"event_id"`
	UserID  string      `json:"user_id"`
}

func (q *Queries) GetAttendee(ctx context.Context, arg GetAttendeeParams) (EventAttendee, error) {
	row := q.db.QueryRow(ctx, getAttendee, arg.EventID, arg.UserID)
	var i EventAttendee
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Rsvp,
		&i.CreatedAt,
	)
	return i, err
}

const getEvent = `-- name: GetEvent :one
SELECT id, host_id, title, event_type, description,
       location_mode, location_address, scheduling_mode, starts_at, status, created_at, comments_enabled, group_id, series_id, recurrence, reminder_sent, visibility, topic, city, custom_emoji, custom_label, general_scope
FROM events
WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id pgtype.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Title,
		&i.EventType,
		&i.Description,
		&i.LocationMode,
		&i.LocationAddress,
		&i.SchedulingMode,
		&i.StartsAt,
		&i.Status,
		&i.CreatedAt,
		&i.CommentsEnabled,
		&i.GroupID,
		&i.SeriesID,
		&i.Recurrence,
		&i.ReminderSent,
		&i.Visibility,
		&i.Topic,
		&i.City,
		&i.CustomEmoji,
		&i.CustomLabel,
		&i.GeneralScope,
	)
	return i, err
}

const getFriendship = `-- name: GetFriendship :one
SELECT id, requester_id, addressee_id, status, created_at
FROM friendships
WHERE id = $1
`

func (q *Queries) GetFriendship(ctx context.Context, id pgtype.UUID) (Friendship, error) {
	row := q.db.QueryRow(ctx, getFriendship, id)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getProfile = `-- name: GetProfile :one

SELECT user_id, display_name, handle, avatar_url, created_at, email
FROM profiles
WHERE user_id = $1
`

type GetProfileRow struct {
	UserID      string             `json:"user_id"`
	DisplayName string             `json:"display_name"`
	Handle      string             `json:"handle"`
	AvatarUrl   string             `json:"avatar_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Email       string             `json:"email"`
}

// ============================ profiles ============================
func (q *Queries) GetProfile(ctx context.Context, userID string) (GetProfileRow, error) {
	row := q.db.QueryRow(ctx, getProfile, userID)
	var i GetProfileRow
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Handle,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.Email,
	)
	return i, err
}

const getProfileByHandle = `-- name: GetProfileByHandle :one
SELECT user_id, display_name, handle, avatar_url, created_at, email
FROM profiles
WHERE handle = $1
`

type GetProfileByHandleRow struct {
	UserID      string             `json:"user_id"`
	DisplayName string             `json:"display_name"`
	Handle      string             `json:"handle"`
	AvatarUrl   string             `json:"avatar_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Email       string             `json:"email"`
}

func (q *Queries) GetProfileByHandle(ctx context.Context, handle string) (GetProfileByHandleRow, error) {
	row := q.db.QueryRow(ctx, getProfileByHandle, handle)
	var i GetProfileByHandleRow
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Handle,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.Email,
	)
	return i, err
}

const listAttendees = `-- name: ListAttendees :many
SELECT a.user_id, a.rsvp, p.display_name, p.avatar_url
FROM event_attendees a
LEFT JOIN profiles p ON p.user_id = a.user_id
WHERE a.event_id = $1
ORDER BY a.created_at
`

type ListAttendeesRow struct {
	UserID      string      `json:"user_id"`
	Rsvp        string      `json:"rsvp"`
	DisplayName pgtype.Text `json:"display_name"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
}

func (q *Queries) ListAttendees(ctx context.Context, eventID pgtype.UUID) ([]ListAttendeesRow, error) {
	rows, err := q.db.Query(ctx, listAttendees, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttendeesRow{}
	for rows.Next() {
		var i ListAttendeesRow
		if err := rows.Scan(
			&i.UserID,
			&i.Rsvp,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailability = `-- name: ListAvailability :many

SELECT user_id, weekday, part_of_day, status
FROM availability_slots
WHERE user_id = $1
ORDER BY weekday, part_of_day
`

// ======================== availability ============================
func (q *Queries) ListAvailability(ctx context.Context, userID string) ([]AvailabilitySlot, error) {
	rows, err := q.db.Query(ctx, listAvailability, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AvailabilitySlot{}
	for rows.Next() {
		var i AvailabilitySlot
		if err := rows.Scan(
			&i.UserID,
			&i.Weekday,
			&i.PartOfDay,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailabilityDays = `-- name: ListAvailabilityDays :many

SELECT day, daypart, status
FROM availability_days
WHERE user_id = $1 AND day >= CURRENT_DATE - INTERVAL '1 day'
ORDER BY day, daypart
`

type ListAvailabilityDaysRow struct {
	Day     pgtype.Date `json:"day"`
	Daypart string      `json:"daypart"`
	Status  string      `json:"status"`
}

// ===================== date-based availability ====================
// The `- 1 day` tolerance keeps "today" from being pruned when the server (UTC)
// is a calendar day ahead of the client's local date — otherwise an evening save
// in a western-hemisphere timezone loses its top (today) row on reload. One extra
// past day is harmless: the client's grid starts at its own local today and never
// renders it.
func (q *Queries) ListAvailabilityDays(ctx context.Context, userID string) ([]ListAvailabilityDaysRow, error) {
	rows, err := q.db.Query(ctx, listAvailabilityDays, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAvailabilityDaysRow{}
	for rows.Next() {
		var i ListAvailabilityDaysRow
		if err := rows.Scan(&i.Day, &i.Daypart, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsAttending = `-- name: ListEventsAttending :many
SELECT e.id, e.host_id, e.title, e.event_type, e.description,
       e.location_mode, e.location_address, e.scheduling_mode, e.starts_at, e.status, e.created_at, e.comments_enabled, e.group_id, e.series_id, e.recurrence, e.reminder_sent, e.visibility, e.topic, e.city, e.custom_emoji, e.custom_label, e.general_scope
FROM events e
JOIN event_attendees a ON a.event_id = e.id
WHERE a.user_id = $1 AND e.host_id <> $1 AND e.status <> 'cancelled'
  AND NOT EXISTS (SELECT 1 FROM event_cohosts ch WHERE ch.event_id = e.id AND ch.user_id = $1)
ORDER BY e.created_at DESC
`

func (q *Queries) ListEventsAttending(ctx context.Context, userID string) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsAttending, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Title,
			&i.EventType,
			&i.Description,
			&i.LocationMode,
			&i.LocationAddress,
			&i.SchedulingMode,
			&i.StartsAt,
			&i.Status,
			&i.CreatedAt,
			&i.CommentsEnabled,
			&i.GroupID,
			&i.SeriesID,
			&i.Recurrence,
			&i.ReminderSent,
			&i.Visibility,
			&i.Topic,
			&i.City,
			&i.CustomEmoji,
			&i.CustomLabel,
			&i.GeneralScope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsCohosting = `-- name: ListEventsCohosting :many
SELECT e.id, e.host_id, e.title, e.event_type, e.description,
       e.location_mode, e.location_address, e.scheduling_mode, e.starts_at, e.status, e.created_at, e.comments_enabled, e.group_id, e.series_id, e.recurrence, e.reminder_sent, e.visibility, e.topic, e.city, e.custom_emoji, e.custom_label, e.general_scope
FROM events e
JOIN event_cohosts ch ON ch.event_id = e.id
WHERE ch.user_id = $1 AND e.status <> 'cancelled'
ORDER BY e.created_at DESC
`

func (q *Queries) ListEventsCohosting(ctx context.Context, userID string) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsCohosting, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Title,
			&i.EventType,
			&i.Description,
			&i.LocationMode,
			&i.LocationAddress,
			&i.SchedulingMode,
			&i.StartsAt,
			&i.Status,
			&i.CreatedAt,
			&i.CommentsEnabled,
			&i.GroupID,
			&i.SeriesID,
			&i.Recurrence,
			&i.ReminderSent,
			&i.Visibility,
			&i.Topic,
			&i.City,
			&i.CustomEmoji,
			&i.CustomLabel,
			&i.GeneralScope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsHosting = `-- name: ListEventsHosting :many
SELECT id, host_id, title, event_type, description,
       location_mode, location_address, scheduling_mode, starts_at, status, created_at, comments_enabled, group_id, series_id, recurrence, reminder_sent, visibility, topic, city, custom_emoji, custom_label, general_scope
FROM events
WHERE host_id = $1 AND status <> 'cancelled'
ORDER BY created_at DESC
`

func (q *Queries) ListEventsHosting(ctx context.Context, hostID string) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsHosting, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Title,
			&i.EventType,
			&i.Description,
			&i.LocationMode,
			&i.LocationAddress,
			&i.SchedulingMode,
			&i.StartsAt,
			&i.Status,
			&i.CreatedAt,
			&i.CommentsEnabled,
			&i.GroupID,
			&i.SeriesID,
			&i.Recurrence,
			&i.ReminderSent,
			&i.Visibility,
			&i.Topic,
			&i.City,
			&i.CustomEmoji,
			&i.CustomLabel,
			&i.GeneralScope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFriends = `-- name: ListFriends :many
SELECT
    f.id,
    (CASE WHEN f.requester_id = $1 THEN f.addressee_id ELSE f.requester_id END)::text AS friend_id,
    p.display_name,
    p.handle,
    p.avatar_url
FROM friendships f
JOIN profiles p
    ON p.user_id = CASE WHEN f.requester_id = $1 THEN f.addressee_id ELSE f.requester_id END
WHERE f.status = 'accepted'
  AND (f.requester_id = $1 OR f.addressee_id = $1)
ORDER BY p.display_name
`

type ListFriendsRow struct {
	ID          pgtype.UUID `json:"id"`
	FriendID    string      `json:"friend_id"`
	DisplayName string      `json:"display_name"`
	Handle      string      `json:"handle"`
	AvatarUrl   string      `json:"avatar_url"`
}

func (q *Queries) ListFriends(ctx context.Context, requesterID string) ([]ListFriendsRow, error) {
	rows, err := q.db.Query(ctx, listFriends, requesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFriendsRow{}
	for rows.Next() {
		var i ListFriendsRow
		if err := rows.Scan(
			&i.ID,
			&i.FriendID,
			&i.DisplayName,
			&i.Handle,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGeneralVotesForEvent = `-- name: ListGeneralVotesForEvent :many
SELECT user_id, dimension, value
FROM event_general_votes
WHERE event_id = $1
`

type ListGeneralVotesForEventRow struct {
	UserID    string `json:"user_id"`
	Dimension string `json:"dimension"`
	Value     string `json:"value"`
}

func (q *Queries) ListGeneralVotesForEvent(ctx context.Context, eventID pgtype.UUID) ([]ListGeneralVotesForEventRow, error) {
	rows, err := q.db.Query(ctx, listGeneralVotesForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGeneralVotesForEventRow{}
	for rows.Next() {
		var i ListGeneralVotesForEventRow
		if err := rows.Scan(&i.UserID, &i.Dimension, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomingRequests = `-- name: ListIncomingRequests :many
SELECT f.id, f.requester_id, p.display_name, p.handle
FROM friendships f
JOIN profiles p ON p.user_id = f.requester_id
WHERE f.addressee_id = $1 AND f.status = 'pending'
ORDER BY f.created_at DESC
`

type ListIncomingRequestsRow struct {
	ID          pgtype.UUID `json:"id"`
	RequesterID string      `json:"requester_id"`
	DisplayName string      `json:"display_name"`
	Handle      string      `json:"handle"`
}

func (q *Queries) ListIncomingRequests(ctx context.Context, addresseeID string) ([]ListIncomingRequestsRow, error) {
	rows, err := q.db.Query(ctx, listIncomingRequests, addresseeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIncomingRequestsRow{}
	for rows.Next() {
		var i ListIncomingRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.RequesterID,
			&i.DisplayName,
			&i.Handle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutgoingRequests = `-- name: ListOutgoingRequests :many
SELECT f.id, f.addressee_id, p.display_name, p.handle
FROM friendships f
JOIN profiles p ON p.user_id = f.addressee_id
WHERE f.requester_id = $1 AND f.status = 'pending'
ORDER BY f.created_at DESC
`

type ListOutgoingRequestsRow struct {
	ID          pgtype.UUID `json:"id"`
	AddresseeID string      `json:"addressee_id"`
	DisplayName string      `json:"display_name"`
	Handle      string      `json:"handle"`
}

func (q *Queries) ListOutgoingRequests(ctx context.Context, requesterID string) ([]ListOutgoingRequestsRow, error) {
	rows, err := q.db.Query(ctx, listOutgoingRequests, requesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOutgoingRequestsRow{}
	for rows.Next() {
		var i ListOutgoingRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.AddresseeID,
			&i.DisplayName,
			&i.Handle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreferenceAnswersForEvent = `-- name: ListPreferenceAnswersForEvent :many
SELECT pa.user_id, pa.question_key, pa.answer, p.display_name
FROM event_preference_answers pa
LEFT JOIN profiles p ON p.user_id = pa.user_id
WHERE pa.event_id = $1
ORDER BY pa.user_id, pa.question_key
`

type ListPreferenceAnswersForEventRow struct {
	UserID      string      `json:"user_id"`
	QuestionKey string      `json:"question_key"`
	Answer      string      `json:"answer"`
	DisplayName pgtype.Text `json:"display_name"`
}

func (q *Queries) ListPreferenceAnswersForEvent(ctx context.Context, eventID pgtype.UUID) ([]ListPreferenceAnswersForEventRow, error) {
	rows, err := q.db.Query(ctx, listPreferenceAnswersForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPreferenceAnswersForEventRow{}
	for rows.Next() {
		var i ListPreferenceAnswersForEventRow
		if err := rows.Scan(
			&i.UserID,
			&i.QuestionKey,
			&i.Answer,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeriesEvents = `-- name: ListSeriesEvents :many
SELECT id, starts_at, status
FROM events
WHERE series_id = $1 AND status <> 'cancelled'
ORDER BY starts_at
`

type ListSeriesEventsRow struct {
	ID       pgtype.UUID        `json:"id"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
	Status   string             `json:"status"`
}

func (q *Queries) ListSeriesEvents(ctx context.Context, seriesID pgtype.UUID) ([]ListSeriesEventsRow, error) {
	rows, err := q.db.Query(ctx, listSeriesEvents, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSeriesEventsRow{}
	for rows.Next() {
		var i ListSeriesEventsRow
		if err := rows.Scan(&i.ID, &i.StartsAt, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimeOptions = `-- name: ListTimeOptions :many
SELECT id, event_id, starts_at
FROM event_time_options
WHERE event_id = $1
ORDER BY starts_at
`

func (q *Queries) ListTimeOptions(ctx context.Context, eventID pgtype.UUID) ([]EventTimeOption, error) {
	rows, err := q.db.Query(ctx, listTimeOptions, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventTimeOption{}
	for rows.Next() {
		var i EventTimeOption
		if err := rows.Scan(&i.ID, &i.EventID, &i.StartsAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingCommitments = `-- name: ListUpcomingCommitments :many
SELECT e.id, e.title, e.starts_at
FROM events e
JOIN event_attendees a ON a.event_id = e.id
WHERE a.user_id = $1 AND a.rsvp = 'going'
  AND e.status = 'scheduled' AND e.starts_at >= now()
ORDER BY e.starts_at
`

type ListUpcomingCommitmentsRow struct {
	ID       pgtype.UUID        `json:"id"`
	Title    string             `json:"title"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
}

func (q *Queries) ListUpcomingCommitments(ctx context.Context, userID string) ([]ListUpcomingCommitmentsRow, error) {
	rows, err := q.db.Query(ctx, listUpcomingCommitments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUpcomingCommitmentsRow{}
	for rows.Next() {
		var i ListUpcomingCommitmentsRow
		if err := rows.Scan(&i.ID, &i.Title, &i.StartsAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVotesForEvent = `-- name: ListVotesForEvent :many
SELECT v.id, v.option_id, v.user_id, v.response
FROM event_time_votes v
JOIN event_time_options o ON o.id = v.option_id
WHERE o.event_id = $1
`

func (q *Queries) ListVotesForEvent(ctx context.Context, eventID pgtype.UUID) ([]EventTimeVote, error) {
	rows, err := q.db.Query(ctx, listVotesForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventTimeVote{}
	for rows.Next() {
		var i EventTimeVote
		if err := rows.Scan(
			&i.ID,
			&i.OptionID,
			&i.UserID,
			&i.Response,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAvatar = `-- name: SetAvatar :one
UPDATE profiles SET avatar_url = $2
WHERE user_id = $1
RETURNING user_id, display_name, handle, avatar_url, created_at, email
`

type SetAvatarParams struct {
	UserID    string `json:"user_id"`
	AvatarUrl string `json:"avatar_url"`
}

type SetAvatarRow struct {
	UserID      string             `json:"user_id"`
	DisplayName string             `json:"display_name"`
	Handle      string             `json:"handle"`
	AvatarUrl   string             `json:"avatar_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Email       string             `json:"email"`
}

func (q *Queries) SetAvatar(ctx context.Context, arg SetAvatarParams) (SetAvatarRow, error) {
	row := q.db.QueryRow(ctx, setAvatar, arg.UserID, arg.AvatarUrl)
	var i SetAvatarRow
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Handle,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.Email,
	)
	return i, err
}

const setCommentsEnabled = `-- name: SetCommentsEnabled :exec
UPDATE events SET comments_enabled = $2 WHERE id = $1
`

type SetCommentsEnabledParams struct {
	ID              pgtype.UUID `json:"id"`
	CommentsEnabled bool        `json:"comments_enabled"`
}

func (q *Queries) SetCommentsEnabled(ctx context.Context, arg SetCommentsEnabledParams) error {
	_, err := q.db.Exec(ctx, setCommentsEnabled, arg.ID, arg.CommentsEnabled)
	return err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET title = $2, description = $3, location_mode = $4, location_address = $5,
    visibility = $6, topic = $7, city = $8
WHERE id = $1
RETURNING id, host_id, title, event_type, description,
          location_mode, location_address, scheduling_mode, starts_at, status, created_at, comments_enabled, group_id, series_id, recurrence, reminder_sent, visibility, topic, city, custom_emoji, custom_label, general_scope
`

type UpdateEventParams struct {
	ID              pgtype.UUID `json:"id"`
	Title           string      `json:"title"`
	Description     string      `json:"description"`
	LocationMode    string      `json:"location_mode"`
	LocationAddress string      `json:"location_address"`
	Visibility      string      `json:"visibility"`
	Topic           string      `json:"topic"`
	City            string      `json:"city"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.LocationMode,
		arg.LocationAddress,
		arg.Visibility,
		arg.Topic,
		arg.City,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Title,
		&i.EventType,
		&i.Description,
		&i.LocationMode,
		&i.LocationAddress,
		&i.SchedulingMode,
		&i.StartsAt,
		&i.Status,
		&i.CreatedAt,
		&i.CommentsEnabled,
		&i.GroupID,
		&i.SeriesID,
		&i.Recurrence,
		&i.ReminderSent,
		&i.Visibility,
		&i.Topic,
		&i.City,
		&i.CustomEmoji,
		&i.CustomLabel,
		&i.GeneralScope,
	)
	return i, err
}

const upsertPreferenceAnswer = `-- name: UpsertPreferenceAnswer :one

INSERT INTO event_preference_answers (event_id, user_id, question_key, answer)
VALUES ($1, $2, $3, $4)
ON CONFLICT (event_id, user_id, question_key) DO UPDATE
    SET answer = EXCLUDED.answer
RETURNING id, event_id, user_id, question_key, answer
`

type UpsertPreferenceAnswerParams struct {
	EventID     pgtype.UUID `json:"event_id"`
	UserID      string      `json:"user_id"`
	QuestionKey string      `json:"question_key"`
	Answer      string      `json:"answer"`
}

// ===================== preference answers =========================
func (q *Queries) UpsertPreferenceAnswer(ctx context.Context, arg UpsertPreferenceAnswerParams) (EventPreferenceAnswer, error) {
	row := q.db.QueryRow(ctx, upsertPreferenceAnswer,
		arg.EventID,
		arg.UserID,
		arg.QuestionKey,
		arg.Answer,
	)
	var i EventPreferenceAnswer
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.QuestionKey,
		&i.Answer,
	)
	return i, err
}

const upsertProfile = `-- name: UpsertProfile :one
INSERT INTO profiles (user_id, display_name, handle, email)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE
    SET display_name = EXCLUDED.display_name,
        handle       = EXCLUDED.handle,
        email        = EXCLUDED.email
RETURNING user_id, display_name, handle, avatar_url, created_at, email
`

type UpsertProfileParams struct {
	UserID      string `json:"user_id"`
	DisplayName string `json:"display_name"`
	Handle      string `json:"handle"`
	Email       string `json:"email"`
}

type UpsertProfileRow struct {
	UserID      string             `json:"user_id"`
	DisplayName string             `json:"display_name"`
	Handle      string             `json:"handle"`
	AvatarUrl   string             `json:"avatar_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Email       string             `json:"email"`
}

func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) (UpsertProfileRow, error) {
	row := q.db.QueryRow(ctx, upsertProfile,
		arg.UserID,
		arg.DisplayName,
		arg.Handle,
		arg.Email,
	)
	var i UpsertProfileRow
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Handle,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.Email,
	)
	return i, err
}

const upsertRsvp = `-- name: UpsertRsvp :one

INSERT INTO event_attendees (event_id, user_id, rsvp)
VALUES ($1, $2, $3)
ON CONFLICT (event_id, user_id) DO UPDATE
    SET rsvp = EXCLUDED.rsvp
RETURNING id, event_id, user_id, rsvp, created_at
`

type UpsertRsvpParams struct {
	EventID pgtype.UUID `json:"event_id"`
	UserID  string      `json:"user_id"`
	Rsvp    string      `json:"rsvp"`
}

// ========================= attendees ==============================
func (q *Queries) UpsertRsvp(ctx context.Context, arg UpsertRsvpParams) (EventAttendee, error) {
	row := q.db.QueryRow(ctx, upsertRsvp, arg.EventID, arg.UserID, arg.Rsvp)
	var i EventAttendee
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Rsvp,
		&i.CreatedAt,
	)
	return i, err
}

const upsertVote = `-- name: UpsertVote :one
INSERT INTO event_time_votes (option_id, user_id, response)
VALUES ($1, $2, $3)
ON CONFLICT (option_id, user_id) DO UPDATE
    SET response = EXCLUDED.response
RETURNING id, option_id, user_id, response
`

type UpsertVoteParams struct {
	OptionID pgtype.UUID `json:"option_id"`
	UserID   string      `json:"user_id"`
	Response string      `json:"response"`
}

func (q *Queries) UpsertVote(ctx context.Context, arg UpsertVoteParams) (EventTimeVote, error) {
	row := q.db.QueryRow(ctx, upsertVote, arg.OptionID, arg.UserID, arg.Response)
	var i EventTimeVote
	err := row.Scan(
		&i.ID,
		&i.OptionID,
		&i.UserID,
		&i.Response,
	)
	return i, err
}
