// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduler.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptFriendRequest = `-- name: AcceptFriendRequest :one
UPDATE friendships
SET status = 'accepted'
WHERE id = $1 AND addressee_id = $2 AND status = 'pending'
RETURNING id, requester_id, addressee_id, status, created_at
`

type AcceptFriendRequestParams struct {
	ID          pgtype.UUID `json:"id"`
	AddresseeID string      `json:"addressee_id"`
}

func (q *Queries) AcceptFriendRequest(ctx context.Context, arg AcceptFriendRequestParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, acceptFriendRequest, arg.ID, arg.AddresseeID)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const addAvailabilityDay = `-- name: AddAvailabilityDay :exec
INSERT INTO availability_days (user_id, day, daypart, status)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type AddAvailabilityDayParams struct {
	UserID  string      `json:"user_id"`
	Day     pgtype.Date `json:"day"`
	Daypart string      `json:"daypart"`
	Status  string      `json:"status"`
}

func (q *Queries) AddAvailabilityDay(ctx context.Context, arg AddAvailabilityDayParams) error {
	_, err := q.db.Exec(ctx, addAvailabilityDay,
		arg.UserID,
		arg.Day,
		arg.Daypart,
		arg.Status,
	)
	return err
}

const addAvailabilitySlot = `-- name: AddAvailabilitySlot :exec
INSERT INTO availability_slots (user_id, weekday, part_of_day, status)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type AddAvailabilitySlotParams struct {
	UserID    string `json:"user_id"`
	Weekday   int16  `json:"weekday"`
	PartOfDay string `json:"part_of_day"`
	Status    string `json:"status"`
}

func (q *Queries) AddAvailabilitySlot(ctx context.Context, arg AddAvailabilitySlotParams) error {
	_, err := q.db.Exec(ctx, addAvailabilitySlot,
		arg.UserID,
		arg.Weekday,
		arg.PartOfDay,
		arg.Status,
	)
	return err
}

const addGeneralVote = `-- name: AddGeneralVote :exec
INSERT INTO event_general_votes (event_id, user_id, dimension, value)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type AddGeneralVoteParams struct {
	EventID   pgtype.UUID `json:"event_id"`
	UserID    string      `json:"user_id"`
	Dimension string      `json:"dimension"`
	Value     string      `json:"value"`
}

func (q *Queries) AddGeneralVote(ctx context.Context, arg AddGeneralVoteParams) error {
	_, err := q.db.Exec(ctx, addGeneralVote,
		arg.EventID,
		arg.UserID,
		arg.Dimension,
		arg.Value,
	)
	return err
}

const addPollDay = `-- name: AddPollDay :exec

INSERT INTO event_poll_days (event_id, day)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddPollDayParams struct {
	EventID pgtype.UUID `json:"event_id"`
	Day     pgtype.Date `json:"day"`
}

// ==================== time-grid ('dates') polls ===================
func (q *Queries) AddPollDay(ctx context.Context, arg AddPollDayParams) error {
	_, err := q.db.Exec(ctx, addPollDay, arg.EventID, arg.Day)
	return err
}

const addTimeOption = `-- name: AddTimeOption :one

INSERT INTO event_time_options (event_id, starts_at)
VALUES ($1, $2)
RETURNING id, event_id, starts_at
`

type AddTimeOptionParams struct {
	EventID  pgtype.UUID        `json:"event_id"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
}

// ====================== event time options ========================
func (q *Queries) AddTimeOption(ctx context.Context, arg AddTimeOptionParams) (EventTimeOption, error) {
	row := q.db.QueryRow(ctx, addTimeOption, arg.EventID, arg.StartsAt)
	var i EventTimeOption
	err := row.Scan(&i.ID, &i.EventID, &i.StartsAt)
	return i, err
}

const areFriends = `-- name: AreFriends :one
SELECT EXISTS (
    SELECT 1 FROM friendships
    WHERE status = 'accepted'
      AND ((requester_id = $1 AND addressee_id = $2)
        OR (requester_id = $2 AND addressee_id = $1))
) AS are_friends
`

type AreFriendsParams struct {
	RequesterID string `json:"requester_id"`
	AddresseeID string `json:"addressee_id"`
}

func (q *Queries) AreFriends(ctx context.Context, arg AreFriendsParams) (bool, error) {
	row := q.db.QueryRow(ctx, areFriends, arg.RequesterID, arg.AddresseeID)
	var are_friends bool
	err := row.Scan(&are_friends)
	return are_friends, err
}

const cancelEvent = `-- name: CancelEvent :one
UPDATE events SET status = 'cancelled'
WHERE id = $1
RETURNING id, host_id, title, event_type, description,
          location_mode, location_address, scheduling_mode, starts_at, status, created_at, comments_enabled, group_id, series_id, recurrence, reminder_sent, visibility, topic, city, custom_emoji, custom_label, general_scope, photo_url, theme, timezone, ends_at, poll_deadline, poll_ready_sent, vote_reminder_sent, quorum_sent, capacity
`

func (q *Queries) CancelEvent(ctx context.Context, id pgtype.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, cancelEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Title,
		&i.EventType,
		&i.Description,
		&i.LocationMode,
		&i.LocationAddress,
		&i.SchedulingMode,
		&i.StartsAt,
		&i.Status,
		&i.CreatedAt,
		&i.CommentsEnabled,
		&i.GroupID,
		&i.SeriesID,
		&i.Recurrence,
		&i.ReminderSent,
		&i.Visibility,
		&i.Topic,
		&i.City,
		&i.CustomEmoji,
		&i.CustomLabel,
		&i.GeneralScope,
		&i.PhotoUrl,
		&i.Theme,
		&i.Timezone,
		&i.EndsAt,
		&i.PollDeadline,
		&i.PollReadySent,
		&i.VoteReminderSent,
		&i.QuorumSent,
		&i.Capacity,
	)
	return i, err
}

const cancelEventQuiet = `-- name: CancelEventQuiet :exec
UPDATE events SET status = 'cancelled' WHERE id = $1
`

// Soft-cancel without the email fan-out (sync-driven: a scraped listing
// vanishing is weaker evidence than a host's explicit cancel).
func (q *Queries) CancelEventQuiet(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, cancelEventQuiet, id)
	return err
}

const cancelSeries = `-- name: CancelSeries :exec
UPDATE events SET status = 'cancelled' WHERE series_id = $1
`

func (q *Queries) CancelSeries(ctx context.Context, seriesID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, cancelSeries, seriesID)
	return err
}

const claimPollReady = `-- name: ClaimPollReady :one
UPDATE events SET poll_ready_sent = true
WHERE id = $1 AND poll_ready_sent = false
RETURNING id
`

// Atomic once-gate (multi-instance + retry safe): a row back means THIS call
// owns the poll-ready send; no row = already sent, skip.
func (q *Queries) ClaimPollReady(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, claimPollReady, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const claimQuorumSent = `-- name: ClaimQuorumSent :one
UPDATE events SET quorum_sent = true
WHERE id = $1 AND quorum_sent = false
RETURNING id
`

// Atomic once-gate (multi-instance safe): no row back = already claimed.
func (q *Queries) ClaimQuorumSent(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, claimQuorumSent, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const claimVoteReminder = `-- name: ClaimVoteReminder :one
UPDATE events SET vote_reminder_sent = true
WHERE id = $1 AND vote_reminder_sent = false
RETURNING id
`

// Atomic once-gate (multi-instance + retry safe): a row back means THIS call
// owns the vote-reminder send; no row = already sent, skip.
func (q *Queries) ClaimVoteReminder(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, claimVoteReminder, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const clearAvailability = `-- name: ClearAvailability :exec
DELETE FROM availability_slots
WHERE user_id = $1
`

func (q *Queries) ClearAvailability(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, clearAvailability, userID)
	return err
}

const clearAvailabilityDays = `-- name: ClearAvailabilityDays :exec
DELETE FROM availability_days
WHERE user_id = $1
`

func (q *Queries) ClearAvailabilityDays(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, clearAvailabilityDays, userID)
	return err
}

const clearGeneralVotes = `-- name: ClearGeneralVotes :exec

DELETE FROM event_general_votes
WHERE event_id = $1 AND user_id = $2
`

type ClearGeneralVotesParams struct {
	EventID pgtype.UUID `json:"event_id"`
	UserID  string      `json:"user_id"`
}

// ====================== general poll votes ========================
func (q *Queries) ClearGeneralVotes(ctx context.Context, arg ClearGeneralVotesParams) error {
	_, err := q.db.Exec(ctx, clearGeneralVotes, arg.EventID, arg.UserID)
	return err
}

const copyAttendees = `-- name: CopyAttendees :exec
INSERT INTO event_attendees (event_id, user_id, rsvp)
SELECT $2::uuid, src.user_id, src.rsvp FROM event_attendees src WHERE src.event_id = $1
ON CONFLICT DO NOTHING
`

type CopyAttendeesParams struct {
	EventID pgtype.UUID `json:"event_id"`
	Column2 pgtype.UUID `json:"column_2"`
}

// Carry everyone (with their RSVP) onto a sibling occurrence.
func (q *Queries) CopyAttendees(ctx context.Context, arg CopyAttendeesParams) error {
	_, err := q.db.Exec(ctx, copyAttendees, arg.EventID, arg.Column2)
	return err
}

const copyInvites = `-- name: CopyInvites :exec
INSERT INTO event_invites (event_id, user_id, inviter_id)
SELECT $2::uuid, src.user_id, src.inviter_id FROM event_invites src WHERE src.event_id = $1
ON CONFLICT DO NOTHING
`

type CopyInvitesParams struct {
	EventID pgtype.UUID `json:"event_id"`
	Column2 pgtype.UUID `json:"column_2"`
}

func (q *Queries) CopyInvites(ctx context.Context, arg CopyInvitesParams) error {
	_, err := q.db.Exec(ctx, copyInvites, arg.EventID, arg.Column2)
	return err
}

const countEventInvites = `-- name: CountEventInvites :one
SELECT count(*)::int FROM event_invites WHERE event_id = $1
`

func (q *Queries) CountEventInvites(ctx context.Context, eventID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countEventInvites, eventID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countGoing = `-- name: CountGoing :one
SELECT count(*)::int FROM event_attendees WHERE event_id = $1 AND rsvp = 'going'
`

// Going-count for one event - rides on the OG unfurl ("4 in so far") so the
// link preview in a group chat carries live social pressure.
func (q *Queries) CountGoing(ctx context.Context, eventID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countGoing, eventID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countInvitedNonVoters = `-- name: CountInvitedNonVoters :one
SELECT count(*)::int FROM event_invites i
WHERE i.event_id = $1
  AND i.user_id NOT IN (
    SELECT gv.user_id FROM event_general_votes gv WHERE gv.event_id = $1
    UNION
    SELECT tv.user_id FROM event_time_votes tv
    JOIN event_time_options o ON o.id = tv.option_id WHERE o.event_id = $1
  )
`

// Quorum check: 0 = every invited person has voted.
func (q *Queries) CountInvitedNonVoters(ctx context.Context, eventID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countInvitedNonVoters, eventID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countNewRegisteredBetween = `-- name: CountNewRegisteredBetween :one
SELECT count(*)::int FROM profiles
WHERE email <> '' AND user_id NOT LIKE 'guest#_%' ESCAPE '#'
  AND created_at >= $1 AND created_at < $2
`

type CountNewRegisteredBetweenParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

func (q *Queries) CountNewRegisteredBetween(ctx context.Context, arg CountNewRegisteredBetweenParams) (int32, error) {
	row := q.db.QueryRow(ctx, countNewRegisteredBetween, arg.CreatedAt, arg.CreatedAt_2)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countRegisteredUsers = `-- name: CountRegisteredUsers :one
SELECT count(*)::int FROM profiles WHERE email <> '' AND user_id NOT LIKE 'guest#_%' ESCAPE '#'
`

// The digest's hero stat: real signups (email on file, not a guest id).
func (q *Queries) CountRegisteredUsers(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countRegisteredUsers)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createEvent = `-- name: CreateEvent :one

INSERT INTO events (
    host_id, title, event_type, description,
    location_mode, location_address, scheduling_mode, starts_at, status, group_id, series_id, recurrence,
    visibility, topic, city, custom_emoji, custom_label, general_scope, timezone, ends_at, poll_deadline, capacity
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22)
RETURNING id, host_id, title, event_type, description,
          location_mode, location_address, scheduling_mode, starts_at, status, created_at, comments_enabled, group_id, series_id, recurrence, reminder_sent, visibility, topic, city, custom_emoji, custom_label, general_scope, photo_url, theme, timezone, ends_at, poll_deadline, poll_ready_sent, vote_reminder_sent, quorum_sent, capacity
`

type CreateEventParams struct {
	HostID          string             `json:"host_id"`
	Title           string             `json:"title"`
	EventType       string             `json:"event_type"`
	Description     string             `json:"description"`
	LocationMode    string             `json:"location_mode"`
	LocationAddress string             `json:"location_address"`
	SchedulingMode  string             `json:"scheduling_mode"`
	StartsAt        pgtype.Timestamptz `json:"starts_at"`
	Status          string             `json:"status"`
	GroupID         pgtype.UUID        `json:"group_id"`
	SeriesID        pgtype.UUID        `json:"series_id"`
	Recurrence      string             `json:"recurrence"`
	Visibility      string             `json:"visibility"`
	Topic           string             `json:"topic"`
	City            string             `json:"city"`
	CustomEmoji     string             `json:"custom_emoji"`
	CustomLabel     string             `json:"custom_label"`
	GeneralScope    string             `json:"general_scope"`
	Timezone        string             `json:"timezone"`
	EndsAt          pgtype.Timestamptz `json:"ends_at"`
	PollDeadline    pgtype.Timestamptz `json:"poll_deadline"`
	Capacity        int32              `json:"capacity"`
}

// =========================== events ===============================
func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.HostID,
		arg.Title,
		arg.EventType,
		arg.Description,
		arg.LocationMode,
		arg.LocationAddress,
		arg.SchedulingMode,
		arg.StartsAt,
		arg.Status,
		arg.GroupID,
		arg.SeriesID,
		arg.Recurrence,
		arg.Visibility,
		arg.Topic,
		arg.City,
		arg.CustomEmoji,
		arg.CustomLabel,
		arg.GeneralScope,
		arg.Timezone,
		arg.EndsAt,
		arg.PollDeadline,
		arg.Capacity,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Title,
		&i.EventType,
		&i.Description,
		&i.LocationMode,
		&i.LocationAddress,
		&i.SchedulingMode,
		&i.StartsAt,
		&i.Status,
		&i.CreatedAt,
		&i.CommentsEnabled,
		&i.GroupID,
		&i.SeriesID,
		&i.Recurrence,
		&i.ReminderSent,
		&i.Visibility,
		&i.Topic,
		&i.City,
		&i.CustomEmoji,
		&i.CustomLabel,
		&i.GeneralScope,
		&i.PhotoUrl,
		&i.Theme,
		&i.Timezone,
		&i.EndsAt,
		&i.PollDeadline,
		&i.PollReadySent,
		&i.VoteReminderSent,
		&i.QuorumSent,
		&i.Capacity,
	)
	return i, err
}

const createFriendRequest = `-- name: CreateFriendRequest :one

INSERT INTO friendships (requester_id, addressee_id)
VALUES ($1, $2)
ON CONFLICT (requester_id, addressee_id) DO NOTHING
RETURNING id, requester_id, addressee_id, status, created_at
`

type CreateFriendRequestParams struct {
	RequesterID string `json:"requester_id"`
	AddresseeID string `json:"addressee_id"`
}

// ========================= friendships ============================
func (q *Queries) CreateFriendRequest(ctx context.Context, arg CreateFriendRequestParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, createFriendRequest, arg.RequesterID, arg.AddresseeID)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const databaseSizeBytes = `-- name: DatabaseSizeBytes :one
SELECT pg_database_size(current_database())::bigint
`

// Digest tier-runway: how close the (image-heavy) database is to the plan cap.
func (q *Queries) DatabaseSizeBytes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, databaseSizeBytes)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteFriendship = `-- name: DeleteFriendship :exec
DELETE FROM friendships WHERE id = $1
`

func (q *Queries) DeleteFriendship(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFriendship, id)
	return err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = $1 AND owner_id = $2
`

type DeleteGroupParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID string      `json:"owner_id"`
}

func (q *Queries) DeleteGroup(ctx context.Context, arg DeleteGroupParams) error {
	_, err := q.db.Exec(ctx, deleteGroup, arg.ID, arg.OwnerID)
	return err
}

const finalizeEvent = `-- name: FinalizeEvent :one
UPDATE events
SET starts_at = $2, status = 'scheduled'
WHERE id = $1
RETURNING id, host_id, title, event_type, description,
          location_mode, location_address, scheduling_mode, starts_at, status, created_at, comments_enabled, group_id, series_id, recurrence, reminder_sent, visibility, topic, city, custom_emoji, custom_label, general_scope, photo_url, theme, timezone, ends_at, poll_deadline, poll_ready_sent, vote_reminder_sent, quorum_sent, capacity
`

type FinalizeEventParams struct {
	ID       pgtype.UUID        `json:"id"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
}

func (q *Queries) FinalizeEvent(ctx context.Context, arg FinalizeEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, finalizeEvent, arg.ID, arg.StartsAt)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Title,
		&i.EventType,
		&i.Description,
		&i.LocationMode,
		&i.LocationAddress,
		&i.SchedulingMode,
		&i.StartsAt,
		&i.Status,
		&i.CreatedAt,
		&i.CommentsEnabled,
		&i.GroupID,
		&i.SeriesID,
		&i.Recurrence,
		&i.ReminderSent,
		&i.Visibility,
		&i.Topic,
		&i.City,
		&i.CustomEmoji,
		&i.CustomLabel,
		&i.GeneralScope,
		&i.PhotoUrl,
		&i.Theme,
		&i.Timezone,
		&i.EndsAt,
		&i.PollDeadline,
		&i.PollReadySent,
		&i.VoteReminderSent,
		&i.QuorumSent,
		&i.Capacity,
	)
	return i, err
}

const getAttendee = `-- name: GetAttendee :one
SELECT id, event_id, user_id, rsvp, created_at, anonymous
FROM event_attendees
WHERE event_id = $1 AND user_id = $2
`

type GetAttendeeParams struct {
	EventID pgtype.UUID `json:"event_id"`
	UserID  string      `json:"user_id"`
}

func (q *Queries) GetAttendee(ctx context.Context, arg GetAttendeeParams) (EventAttendee, error) {
	row := q.db.QueryRow(ctx, getAttendee, arg.EventID, arg.UserID)
	var i EventAttendee
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Rsvp,
		&i.CreatedAt,
		&i.Anonymous,
	)
	return i, err
}

const getEvent = `-- name: GetEvent :one
SELECT id, host_id, title, event_type, description,
       location_mode, location_address, scheduling_mode, starts_at, status, created_at, comments_enabled, group_id, series_id, recurrence, reminder_sent, visibility, topic, city, custom_emoji, custom_label, general_scope, photo_url, theme, timezone, ends_at, poll_deadline, poll_ready_sent, vote_reminder_sent, quorum_sent, capacity
FROM events
WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id pgtype.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Title,
		&i.EventType,
		&i.Description,
		&i.LocationMode,
		&i.LocationAddress,
		&i.SchedulingMode,
		&i.StartsAt,
		&i.Status,
		&i.CreatedAt,
		&i.CommentsEnabled,
		&i.GroupID,
		&i.SeriesID,
		&i.Recurrence,
		&i.ReminderSent,
		&i.Visibility,
		&i.Topic,
		&i.City,
		&i.CustomEmoji,
		&i.CustomLabel,
		&i.GeneralScope,
		&i.PhotoUrl,
		&i.Theme,
		&i.Timezone,
		&i.EndsAt,
		&i.PollDeadline,
		&i.PollReadySent,
		&i.VoteReminderSent,
		&i.QuorumSent,
		&i.Capacity,
	)
	return i, err
}

const getFriendship = `-- name: GetFriendship :one
SELECT id, requester_id, addressee_id, status, created_at
FROM friendships
WHERE id = $1
`

func (q *Queries) GetFriendship(ctx context.Context, id pgtype.UUID) (Friendship, error) {
	row := q.db.QueryRow(ctx, getFriendship, id)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPollTimeGrid = `-- name: GetPollTimeGrid :one
SELECT start_min, end_min, slot_min
FROM event_poll_time_grid
WHERE event_id = $1
`

type GetPollTimeGridRow struct {
	StartMin int32 `json:"start_min"`
	EndMin   int32 `json:"end_min"`
	SlotMin  int32 `json:"slot_min"`
}

func (q *Queries) GetPollTimeGrid(ctx context.Context, eventID pgtype.UUID) (GetPollTimeGridRow, error) {
	row := q.db.QueryRow(ctx, getPollTimeGrid, eventID)
	var i GetPollTimeGridRow
	err := row.Scan(&i.StartMin, &i.EndMin, &i.SlotMin)
	return i, err
}

const getProfile = `-- name: GetProfile :one

SELECT user_id, display_name, handle, avatar_url, created_at, email
FROM profiles
WHERE user_id = $1
`

type GetProfileRow struct {
	UserID      string             `json:"user_id"`
	DisplayName string             `json:"display_name"`
	Handle      string             `json:"handle"`
	AvatarUrl   string             `json:"avatar_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Email       string             `json:"email"`
}

// ============================ profiles ============================
func (q *Queries) GetProfile(ctx context.Context, userID string) (GetProfileRow, error) {
	row := q.db.QueryRow(ctx, getProfile, userID)
	var i GetProfileRow
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Handle,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.Email,
	)
	return i, err
}

const getProfileByHandle = `-- name: GetProfileByHandle :one
SELECT user_id, display_name, handle, avatar_url, created_at, email
FROM profiles
WHERE handle = $1
`

type GetProfileByHandleRow struct {
	UserID      string             `json:"user_id"`
	DisplayName string             `json:"display_name"`
	Handle      string             `json:"handle"`
	AvatarUrl   string             `json:"avatar_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Email       string             `json:"email"`
}

func (q *Queries) GetProfileByHandle(ctx context.Context, handle string) (GetProfileByHandleRow, error) {
	row := q.db.QueryRow(ctx, getProfileByHandle, handle)
	var i GetProfileByHandleRow
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Handle,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.Email,
	)
	return i, err
}

const listAttendeeAvailabilityForEvent = `-- name: ListAttendeeAvailabilityForEvent :many
SELECT ad.user_id, ad.day, ad.daypart, ad.status
FROM availability_days ad
WHERE ad.user_id IN (SELECT user_id FROM event_attendees WHERE event_id = $1)
`

// Every attendee's date-based availability — the input for ranking a poll's
// candidate times against the WHOLE group, not just the viewer.
func (q *Queries) ListAttendeeAvailabilityForEvent(ctx context.Context, eventID pgtype.UUID) ([]AvailabilityDay, error) {
	rows, err := q.db.Query(ctx, listAttendeeAvailabilityForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AvailabilityDay{}
	for rows.Next() {
		var i AvailabilityDay
		if err := rows.Scan(
			&i.UserID,
			&i.Day,
			&i.Daypart,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttendees = `-- name: ListAttendees :many
SELECT a.user_id, a.rsvp, a.anonymous, p.display_name, p.avatar_url, p.handle
FROM event_attendees a
LEFT JOIN profiles p ON p.user_id = a.user_id
WHERE a.event_id = $1
ORDER BY a.created_at
`

type ListAttendeesRow struct {
	UserID      string      `json:"user_id"`
	Rsvp        string      `json:"rsvp"`
	Anonymous   bool        `json:"anonymous"`
	DisplayName pgtype.Text `json:"display_name"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	Handle      pgtype.Text `json:"handle"`
}

func (q *Queries) ListAttendees(ctx context.Context, eventID pgtype.UUID) ([]ListAttendeesRow, error) {
	rows, err := q.db.Query(ctx, listAttendees, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttendeesRow{}
	for rows.Next() {
		var i ListAttendeesRow
		if err := rows.Scan(
			&i.UserID,
			&i.Rsvp,
			&i.Anonymous,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Handle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailability = `-- name: ListAvailability :many

SELECT user_id, weekday, part_of_day, status
FROM availability_slots
WHERE user_id = $1
ORDER BY weekday, part_of_day
`

// ======================== availability ============================
func (q *Queries) ListAvailability(ctx context.Context, userID string) ([]AvailabilitySlot, error) {
	rows, err := q.db.Query(ctx, listAvailability, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AvailabilitySlot{}
	for rows.Next() {
		var i AvailabilitySlot
		if err := rows.Scan(
			&i.UserID,
			&i.Weekday,
			&i.PartOfDay,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailabilityDays = `-- name: ListAvailabilityDays :many

SELECT day, daypart, status
FROM availability_days
WHERE user_id = $1 AND day >= CURRENT_DATE - INTERVAL '1 day'
ORDER BY day, daypart
`

type ListAvailabilityDaysRow struct {
	Day     pgtype.Date `json:"day"`
	Daypart string      `json:"daypart"`
	Status  string      `json:"status"`
}

// ===================== date-based availability ====================
// The `- 1 day` tolerance keeps "today" from being pruned when the server (UTC)
// is a calendar day ahead of the client's local date — otherwise an evening save
// in a western-hemisphere timezone loses its top (today) row on reload. One extra
// past day is harmless: the client's grid starts at its own local today and never
// renders it.
func (q *Queries) ListAvailabilityDays(ctx context.Context, userID string) ([]ListAvailabilityDaysRow, error) {
	rows, err := q.db.Query(ctx, listAvailabilityDays, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAvailabilityDaysRow{}
	for rows.Next() {
		var i ListAvailabilityDaysRow
		if err := rows.Scan(&i.Day, &i.Daypart, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsAttending = `-- name: ListEventsAttending :many
SELECT e.id, e.host_id, e.title, e.event_type, e.description,
       e.location_mode, e.location_address, e.scheduling_mode, e.starts_at, e.status, e.created_at, e.comments_enabled, e.group_id, e.series_id, e.recurrence, e.reminder_sent, e.visibility, e.topic, e.city, e.custom_emoji, e.custom_label, e.general_scope, e.photo_url, e.theme, e.timezone, e.ends_at, e.poll_deadline, e.poll_ready_sent, e.vote_reminder_sent, e.quorum_sent, e.capacity
FROM events e
JOIN event_attendees a ON a.event_id = e.id
WHERE a.user_id = $1 AND e.host_id <> $1 AND e.status <> 'cancelled' AND e.status <> 'draft'
  AND NOT EXISTS (SELECT 1 FROM event_cohosts ch WHERE ch.event_id = e.id AND ch.user_id = $1)
ORDER BY e.created_at DESC
`

func (q *Queries) ListEventsAttending(ctx context.Context, userID string) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsAttending, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Title,
			&i.EventType,
			&i.Description,
			&i.LocationMode,
			&i.LocationAddress,
			&i.SchedulingMode,
			&i.StartsAt,
			&i.Status,
			&i.CreatedAt,
			&i.CommentsEnabled,
			&i.GroupID,
			&i.SeriesID,
			&i.Recurrence,
			&i.ReminderSent,
			&i.Visibility,
			&i.Topic,
			&i.City,
			&i.CustomEmoji,
			&i.CustomLabel,
			&i.GeneralScope,
			&i.PhotoUrl,
			&i.Theme,
			&i.Timezone,
			&i.EndsAt,
			&i.PollDeadline,
			&i.PollReadySent,
			&i.VoteReminderSent,
			&i.QuorumSent,
			&i.Capacity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsCohosting = `-- name: ListEventsCohosting :many
SELECT e.id, e.host_id, e.title, e.event_type, e.description,
       e.location_mode, e.location_address, e.scheduling_mode, e.starts_at, e.status, e.created_at, e.comments_enabled, e.group_id, e.series_id, e.recurrence, e.reminder_sent, e.visibility, e.topic, e.city, e.custom_emoji, e.custom_label, e.general_scope, e.photo_url, e.theme, e.timezone, e.ends_at, e.poll_deadline, e.poll_ready_sent, e.vote_reminder_sent, e.quorum_sent, e.capacity
FROM events e
JOIN event_cohosts ch ON ch.event_id = e.id
WHERE ch.user_id = $1 AND e.status <> 'cancelled'
ORDER BY e.created_at DESC
`

func (q *Queries) ListEventsCohosting(ctx context.Context, userID string) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsCohosting, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Title,
			&i.EventType,
			&i.Description,
			&i.LocationMode,
			&i.LocationAddress,
			&i.SchedulingMode,
			&i.StartsAt,
			&i.Status,
			&i.CreatedAt,
			&i.CommentsEnabled,
			&i.GroupID,
			&i.SeriesID,
			&i.Recurrence,
			&i.ReminderSent,
			&i.Visibility,
			&i.Topic,
			&i.City,
			&i.CustomEmoji,
			&i.CustomLabel,
			&i.GeneralScope,
			&i.PhotoUrl,
			&i.Theme,
			&i.Timezone,
			&i.EndsAt,
			&i.PollDeadline,
			&i.PollReadySent,
			&i.VoteReminderSent,
			&i.QuorumSent,
			&i.Capacity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsHosting = `-- name: ListEventsHosting :many
SELECT id, host_id, title, event_type, description,
       location_mode, location_address, scheduling_mode, starts_at, status, created_at, comments_enabled, group_id, series_id, recurrence, reminder_sent, visibility, topic, city, custom_emoji, custom_label, general_scope, photo_url, theme, timezone, ends_at, poll_deadline, poll_ready_sent, vote_reminder_sent, quorum_sent, capacity
FROM events
WHERE host_id = $1 AND status <> 'cancelled'
ORDER BY created_at DESC
`

func (q *Queries) ListEventsHosting(ctx context.Context, hostID string) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsHosting, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Title,
			&i.EventType,
			&i.Description,
			&i.LocationMode,
			&i.LocationAddress,
			&i.SchedulingMode,
			&i.StartsAt,
			&i.Status,
			&i.CreatedAt,
			&i.CommentsEnabled,
			&i.GroupID,
			&i.SeriesID,
			&i.Recurrence,
			&i.ReminderSent,
			&i.Visibility,
			&i.Topic,
			&i.City,
			&i.CustomEmoji,
			&i.CustomLabel,
			&i.GeneralScope,
			&i.PhotoUrl,
			&i.Theme,
			&i.Timezone,
			&i.EndsAt,
			&i.PollDeadline,
			&i.PollReadySent,
			&i.VoteReminderSent,
			&i.QuorumSent,
			&i.Capacity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFriends = `-- name: ListFriends :many
SELECT
    f.id,
    (CASE WHEN f.requester_id = $1 THEN f.addressee_id ELSE f.requester_id END)::text AS friend_id,
    p.display_name,
    p.handle,
    p.avatar_url
FROM friendships f
JOIN profiles p
    ON p.user_id = CASE WHEN f.requester_id = $1 THEN f.addressee_id ELSE f.requester_id END
WHERE f.status = 'accepted'
  AND (f.requester_id = $1 OR f.addressee_id = $1)
ORDER BY p.display_name
`

type ListFriendsRow struct {
	ID          pgtype.UUID `json:"id"`
	FriendID    string      `json:"friend_id"`
	DisplayName string      `json:"display_name"`
	Handle      string      `json:"handle"`
	AvatarUrl   string      `json:"avatar_url"`
}

func (q *Queries) ListFriends(ctx context.Context, requesterID string) ([]ListFriendsRow, error) {
	rows, err := q.db.Query(ctx, listFriends, requesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFriendsRow{}
	for rows.Next() {
		var i ListFriendsRow
		if err := rows.Scan(
			&i.ID,
			&i.FriendID,
			&i.DisplayName,
			&i.Handle,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGeneralTopCells = `-- name: ListGeneralTopCells :many
SELECT value, count(*)::int AS votes
FROM event_general_votes
WHERE event_id = $1 AND dimension IN ('dayslot', 'slot', 'day')
GROUP BY value
ORDER BY votes DESC, value
LIMIT 3
`

type ListGeneralTopCellsRow struct {
	Value string `json:"value"`
	Votes int32  `json:"votes"`
}

// Top-voted general-poll cells for the poll-ready email.
func (q *Queries) ListGeneralTopCells(ctx context.Context, eventID pgtype.UUID) ([]ListGeneralTopCellsRow, error) {
	rows, err := q.db.Query(ctx, listGeneralTopCells, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGeneralTopCellsRow{}
	for rows.Next() {
		var i ListGeneralTopCellsRow
		if err := rows.Scan(&i.Value, &i.Votes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGeneralVotesForEvent = `-- name: ListGeneralVotesForEvent :many
SELECT user_id, dimension, value
FROM event_general_votes
WHERE event_id = $1
`

type ListGeneralVotesForEventRow struct {
	UserID    string `json:"user_id"`
	Dimension string `json:"dimension"`
	Value     string `json:"value"`
}

func (q *Queries) ListGeneralVotesForEvent(ctx context.Context, eventID pgtype.UUID) ([]ListGeneralVotesForEventRow, error) {
	rows, err := q.db.Query(ctx, listGeneralVotesForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGeneralVotesForEventRow{}
	for rows.Next() {
		var i ListGeneralVotesForEventRow
		if err := rows.Scan(&i.UserID, &i.Dimension, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoingFaces = `-- name: ListGoingFaces :many
SELECT event_id, user_id, display_name, avatar_url, is_friend, going_count
FROM (
    SELECT a.event_id, a.user_id, a.anonymous,
           COALESCE(p.display_name, 'Guest') AS display_name,
           COALESCE(p.avatar_url, '')        AS avatar_url,
           EXISTS (
               SELECT 1 FROM friendships f WHERE f.status = 'accepted'
                 AND ((f.requester_id = $1 AND f.addressee_id = a.user_id)
                   OR (f.requester_id = a.user_id AND f.addressee_id = $1))
           ) AS is_friend,
           count(*) OVER (PARTITION BY a.event_id)::int AS going_count,
           row_number() OVER (
               PARTITION BY a.event_id
               ORDER BY a.anonymous ASC,
                        EXISTS (
                            SELECT 1 FROM friendships f WHERE f.status = 'accepted'
                              AND ((f.requester_id = $1 AND f.addressee_id = a.user_id)
                                OR (f.requester_id = a.user_id AND f.addressee_id = $1))
                        ) DESC,
                        (COALESCE(p.avatar_url, '') <> '') DESC,
                        COALESCE(p.display_name, '')
           ) AS rn
    FROM event_attendees a
    LEFT JOIN profiles p ON p.user_id = a.user_id
    WHERE a.rsvp = 'going' AND a.event_id = ANY($2::uuid[])
) x
WHERE rn <= 6 AND NOT anonymous
`

type ListGoingFacesParams struct {
	RequesterID string        `json:"requester_id"`
	Column2     []pgtype.UUID `json:"column_2"`
}

type ListGoingFacesRow struct {
	EventID     pgtype.UUID `json:"event_id"`
	UserID      string      `json:"user_id"`
	DisplayName string      `json:"display_name"`
	AvatarUrl   string      `json:"avatar_url"`
	IsFriend    bool        `json:"is_friend"`
	GoingCount  int32       `json:"going_count"`
}

// Avatar-stack preview for event tiles: up to 6 'going' attendees per event,
// prioritized for the viewer — friends first, then people with a photo, then
// initials-only — plus the total going count for the "+N more" tail.
func (q *Queries) ListGoingFaces(ctx context.Context, arg ListGoingFacesParams) ([]ListGoingFacesRow, error) {
	rows, err := q.db.Query(ctx, listGoingFaces, arg.RequesterID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGoingFacesRow{}
	for rows.Next() {
		var i ListGoingFacesRow
		if err := rows.Scan(
			&i.EventID,
			&i.UserID,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.IsFriend,
			&i.GoingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomingRequests = `-- name: ListIncomingRequests :many
SELECT f.id, f.requester_id, p.display_name, p.handle
FROM friendships f
JOIN profiles p ON p.user_id = f.requester_id
WHERE f.addressee_id = $1 AND f.status = 'pending'
ORDER BY f.created_at DESC
`

type ListIncomingRequestsRow struct {
	ID          pgtype.UUID `json:"id"`
	RequesterID string      `json:"requester_id"`
	DisplayName string      `json:"display_name"`
	Handle      string      `json:"handle"`
}

func (q *Queries) ListIncomingRequests(ctx context.Context, addresseeID string) ([]ListIncomingRequestsRow, error) {
	rows, err := q.db.Query(ctx, listIncomingRequests, addresseeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIncomingRequestsRow{}
	for rows.Next() {
		var i ListIncomingRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.RequesterID,
			&i.DisplayName,
			&i.Handle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvitedNonVoterContacts = `-- name: ListInvitedNonVoterContacts :many
SELECT p.user_id, p.display_name, p.email
FROM event_invites i
JOIN profiles p ON p.user_id = i.user_id
WHERE i.event_id = $1 AND p.email <> ''
  AND p.user_id NOT IN (
    SELECT gv.user_id FROM event_general_votes gv WHERE gv.event_id = $1
    UNION
    SELECT tv.user_id FROM event_time_votes tv
    JOIN event_time_options o ON o.id = tv.option_id WHERE o.event_id = $1
  )
`

type ListInvitedNonVoterContactsRow struct {
	UserID      string `json:"user_id"`
	DisplayName string `json:"display_name"`
	Email       string `json:"email"`
}

// Invitees with an email who haven't voted on this poll (any dimension).
func (q *Queries) ListInvitedNonVoterContacts(ctx context.Context, eventID pgtype.UUID) ([]ListInvitedNonVoterContactsRow, error) {
	rows, err := q.db.Query(ctx, listInvitedNonVoterContacts, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvitedNonVoterContactsRow{}
	for rows.Next() {
		var i ListInvitedNonVoterContactsRow
		if err := rows.Scan(&i.UserID, &i.DisplayName, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyRsvps = `-- name: ListMyRsvps :many
SELECT event_id, rsvp FROM event_attendees WHERE user_id = $1
`

type ListMyRsvpsRow struct {
	EventID pgtype.UUID `json:"event_id"`
	Rsvp    string      `json:"rsvp"`
}

// The viewer's own rsvp per event - dashboard tiles use it to render
// Attended vs Passed on past events.
func (q *Queries) ListMyRsvps(ctx context.Context, userID string) ([]ListMyRsvpsRow, error) {
	rows, err := q.db.Query(ctx, listMyRsvps, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyRsvpsRow{}
	for rows.Next() {
		var i ListMyRsvpsRow
		if err := rows.Scan(&i.EventID, &i.Rsvp); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOldestWaitlist = `-- name: ListOldestWaitlist :one
SELECT user_id FROM event_attendees
WHERE event_id = $1 AND rsvp = 'waitlist'
ORDER BY created_at
LIMIT 1
`

// Next in line when a going spot frees up.
func (q *Queries) ListOldestWaitlist(ctx context.Context, eventID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, listOldestWaitlist, eventID)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const listOptionYesCounts = `-- name: ListOptionYesCounts :many
SELECT o.starts_at, count(v.user_id) FILTER (WHERE v.response = 'yes')::int AS yes
FROM event_time_options o
LEFT JOIN event_time_votes v ON v.option_id = o.id
WHERE o.event_id = $1
GROUP BY o.id, o.starts_at
ORDER BY yes DESC, o.starts_at
LIMIT 3
`

type ListOptionYesCountsRow struct {
	StartsAt pgtype.Timestamptz `json:"starts_at"`
	Yes      int32              `json:"yes"`
}

// Winning options for the poll-ready email, best first.
func (q *Queries) ListOptionYesCounts(ctx context.Context, eventID pgtype.UUID) ([]ListOptionYesCountsRow, error) {
	rows, err := q.db.Query(ctx, listOptionYesCounts, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOptionYesCountsRow{}
	for rows.Next() {
		var i ListOptionYesCountsRow
		if err := rows.Scan(&i.StartsAt, &i.Yes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutgoingRequests = `-- name: ListOutgoingRequests :many
SELECT f.id, f.addressee_id, p.display_name, p.handle
FROM friendships f
JOIN profiles p ON p.user_id = f.addressee_id
WHERE f.requester_id = $1 AND f.status = 'pending'
ORDER BY f.created_at DESC
`

type ListOutgoingRequestsRow struct {
	ID          pgtype.UUID `json:"id"`
	AddresseeID string      `json:"addressee_id"`
	DisplayName string      `json:"display_name"`
	Handle      string      `json:"handle"`
}

func (q *Queries) ListOutgoingRequests(ctx context.Context, requesterID string) ([]ListOutgoingRequestsRow, error) {
	rows, err := q.db.Query(ctx, listOutgoingRequests, requesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOutgoingRequestsRow{}
	for rows.Next() {
		var i ListOutgoingRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.AddresseeID,
			&i.DisplayName,
			&i.Handle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPollDays = `-- name: ListPollDays :many
SELECT day
FROM event_poll_days
WHERE event_id = $1
ORDER BY day
`

func (q *Queries) ListPollDays(ctx context.Context, eventID pgtype.UUID) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, listPollDays, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Date{}
	for rows.Next() {
		var day pgtype.Date
		if err := rows.Scan(&day); err != nil {
			return nil, err
		}
		items = append(items, day)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPollsNeedingVoteReminder = `-- name: ListPollsNeedingVoteReminder :many
SELECT id, host_id, title, event_type, description,
       location_mode, location_address, scheduling_mode, starts_at, status, created_at, comments_enabled, group_id, series_id, recurrence, reminder_sent, visibility, topic, city, custom_emoji, custom_label, general_scope, photo_url, theme, timezone, ends_at, poll_deadline, poll_ready_sent, vote_reminder_sent, quorum_sent, capacity
FROM events
WHERE status = 'polling' AND poll_deadline IS NOT NULL
  AND poll_deadline > now() AND poll_deadline <= now() + interval '26 hours'
  AND vote_reminder_sent = false
`

// Polls closing within the next cron day - invited non-voters get one
// last-chance email (vote_reminder_sent gate).
func (q *Queries) ListPollsNeedingVoteReminder(ctx context.Context) ([]Event, error) {
	rows, err := q.db.Query(ctx, listPollsNeedingVoteReminder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Title,
			&i.EventType,
			&i.Description,
			&i.LocationMode,
			&i.LocationAddress,
			&i.SchedulingMode,
			&i.StartsAt,
			&i.Status,
			&i.CreatedAt,
			&i.CommentsEnabled,
			&i.GroupID,
			&i.SeriesID,
			&i.Recurrence,
			&i.ReminderSent,
			&i.Visibility,
			&i.Topic,
			&i.City,
			&i.CustomEmoji,
			&i.CustomLabel,
			&i.GeneralScope,
			&i.PhotoUrl,
			&i.Theme,
			&i.Timezone,
			&i.EndsAt,
			&i.PollDeadline,
			&i.PollReadySent,
			&i.VoteReminderSent,
			&i.QuorumSent,
			&i.Capacity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPollsPastDeadline = `-- name: ListPollsPastDeadline :many
SELECT id, host_id, title, event_type, description,
       location_mode, location_address, scheduling_mode, starts_at, status, created_at, comments_enabled, group_id, series_id, recurrence, reminder_sent, visibility, topic, city, custom_emoji, custom_label, general_scope, photo_url, theme, timezone, ends_at, poll_deadline, poll_ready_sent, vote_reminder_sent, quorum_sent, capacity
FROM events
WHERE status = 'polling' AND poll_deadline IS NOT NULL
  AND poll_deadline < now() AND poll_ready_sent = false
`

// Polls whose close date passed without the host locking a time - the cron
// emails the host ONCE with the winning options (poll_ready_sent gate).
func (q *Queries) ListPollsPastDeadline(ctx context.Context) ([]Event, error) {
	rows, err := q.db.Query(ctx, listPollsPastDeadline)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Title,
			&i.EventType,
			&i.Description,
			&i.LocationMode,
			&i.LocationAddress,
			&i.SchedulingMode,
			&i.StartsAt,
			&i.Status,
			&i.CreatedAt,
			&i.CommentsEnabled,
			&i.GroupID,
			&i.SeriesID,
			&i.Recurrence,
			&i.ReminderSent,
			&i.Visibility,
			&i.Topic,
			&i.City,
			&i.CustomEmoji,
			&i.CustomLabel,
			&i.GeneralScope,
			&i.PhotoUrl,
			&i.Theme,
			&i.Timezone,
			&i.EndsAt,
			&i.PollDeadline,
			&i.PollReadySent,
			&i.VoteReminderSent,
			&i.QuorumSent,
			&i.Capacity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreferenceAnswersForEvent = `-- name: ListPreferenceAnswersForEvent :many
SELECT pa.user_id, pa.question_key, pa.answer, p.display_name
FROM event_preference_answers pa
LEFT JOIN profiles p ON p.user_id = pa.user_id
WHERE pa.event_id = $1
ORDER BY pa.user_id, pa.question_key
`

type ListPreferenceAnswersForEventRow struct {
	UserID      string      `json:"user_id"`
	QuestionKey string      `json:"question_key"`
	Answer      string      `json:"answer"`
	DisplayName pgtype.Text `json:"display_name"`
}

func (q *Queries) ListPreferenceAnswersForEvent(ctx context.Context, eventID pgtype.UUID) ([]ListPreferenceAnswersForEventRow, error) {
	rows, err := q.db.Query(ctx, listPreferenceAnswersForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPreferenceAnswersForEventRow{}
	for rows.Next() {
		var i ListPreferenceAnswersForEventRow
		if err := rows.Scan(
			&i.UserID,
			&i.QuestionKey,
			&i.Answer,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeriesEvents = `-- name: ListSeriesEvents :many
SELECT id, starts_at, status
FROM events
WHERE series_id = $1 AND status <> 'cancelled'
ORDER BY starts_at
`

type ListSeriesEventsRow struct {
	ID       pgtype.UUID        `json:"id"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
	Status   string             `json:"status"`
}

func (q *Queries) ListSeriesEvents(ctx context.Context, seriesID pgtype.UUID) ([]ListSeriesEventsRow, error) {
	rows, err := q.db.Query(ctx, listSeriesEvents, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSeriesEventsRow{}
	for rows.Next() {
		var i ListSeriesEventsRow
		if err := rows.Scan(&i.ID, &i.StartsAt, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimeOptions = `-- name: ListTimeOptions :many
SELECT id, event_id, starts_at
FROM event_time_options
WHERE event_id = $1
ORDER BY starts_at
`

func (q *Queries) ListTimeOptions(ctx context.Context, eventID pgtype.UUID) ([]EventTimeOption, error) {
	rows, err := q.db.Query(ctx, listTimeOptions, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventTimeOption{}
	for rows.Next() {
		var i EventTimeOption
		if err := rows.Scan(&i.ID, &i.EventID, &i.StartsAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingCommitments = `-- name: ListUpcomingCommitments :many
SELECT e.id, e.title, e.starts_at
FROM events e
JOIN event_attendees a ON a.event_id = e.id
WHERE a.user_id = $1 AND a.rsvp = 'going'
  AND e.status = 'scheduled' AND e.starts_at >= now()
ORDER BY e.starts_at
`

type ListUpcomingCommitmentsRow struct {
	ID       pgtype.UUID        `json:"id"`
	Title    string             `json:"title"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
}

func (q *Queries) ListUpcomingCommitments(ctx context.Context, userID string) ([]ListUpcomingCommitmentsRow, error) {
	rows, err := q.db.Query(ctx, listUpcomingCommitments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUpcomingCommitmentsRow{}
	for rows.Next() {
		var i ListUpcomingCommitmentsRow
		if err := rows.Scan(&i.ID, &i.Title, &i.StartsAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVoterProfiles = `-- name: ListVoterProfiles :many
SELECT DISTINCT p.user_id, p.display_name, p.avatar_url
FROM profiles p
WHERE p.user_id IN (
    SELECT gv.user_id FROM event_general_votes gv WHERE gv.event_id = $1::uuid
    UNION
    SELECT tv.user_id FROM event_time_votes tv
    JOIN event_time_options o ON o.id = tv.option_id
    WHERE o.event_id = $1::uuid
)
`

type ListVoterProfilesRow struct {
	UserID      string `json:"user_id"`
	DisplayName string `json:"display_name"`
	AvatarUrl   string `json:"avatar_url"`
}

// Names/avatars for everyone who responded to a poll (general votes or
// specific-time votes) — a pure voter has no attendee row, so the responder
// dots can't rely on the attendee list alone.
func (q *Queries) ListVoterProfiles(ctx context.Context, dollar_1 pgtype.UUID) ([]ListVoterProfilesRow, error) {
	rows, err := q.db.Query(ctx, listVoterProfiles, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVoterProfilesRow{}
	for rows.Next() {
		var i ListVoterProfilesRow
		if err := rows.Scan(&i.UserID, &i.DisplayName, &i.AvatarUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVotesForEvent = `-- name: ListVotesForEvent :many
SELECT v.id, v.option_id, v.user_id, v.response
FROM event_time_votes v
JOIN event_time_options o ON o.id = v.option_id
WHERE o.event_id = $1
`

func (q *Queries) ListVotesForEvent(ctx context.Context, eventID pgtype.UUID) ([]EventTimeVote, error) {
	rows, err := q.db.Query(ctx, listVotesForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventTimeVote{}
	for rows.Next() {
		var i EventTimeVote
		if err := rows.Scan(
			&i.ID,
			&i.OptionID,
			&i.UserID,
			&i.Response,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteAttendee = `-- name: PromoteAttendee :exec
UPDATE event_attendees SET rsvp = 'going' WHERE event_id = $1 AND user_id = $2 AND rsvp = 'waitlist'
`

type PromoteAttendeeParams struct {
	EventID pgtype.UUID `json:"event_id"`
	UserID  string      `json:"user_id"`
}

func (q *Queries) PromoteAttendee(ctx context.Context, arg PromoteAttendeeParams) error {
	_, err := q.db.Exec(ctx, promoteAttendee, arg.EventID, arg.UserID)
	return err
}

const retimeEvent = `-- name: RetimeEvent :exec
UPDATE events SET starts_at = $2, reminder_sent = false WHERE id = $1
`

type RetimeEventParams struct {
	ID       pgtype.UUID        `json:"id"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
}

// Move a scheduled occurrence (venue time changed upstream): new start,
// reminder re-armed so the day-before email fires for the new date.
func (q *Queries) RetimeEvent(ctx context.Context, arg RetimeEventParams) error {
	_, err := q.db.Exec(ctx, retimeEvent, arg.ID, arg.StartsAt)
	return err
}

const setAvatar = `-- name: SetAvatar :one
UPDATE profiles SET avatar_url = $2
WHERE user_id = $1
RETURNING user_id, display_name, handle, avatar_url, created_at, email
`

type SetAvatarParams struct {
	UserID    string `json:"user_id"`
	AvatarUrl string `json:"avatar_url"`
}

type SetAvatarRow struct {
	UserID      string             `json:"user_id"`
	DisplayName string             `json:"display_name"`
	Handle      string             `json:"handle"`
	AvatarUrl   string             `json:"avatar_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Email       string             `json:"email"`
}

func (q *Queries) SetAvatar(ctx context.Context, arg SetAvatarParams) (SetAvatarRow, error) {
	row := q.db.QueryRow(ctx, setAvatar, arg.UserID, arg.AvatarUrl)
	var i SetAvatarRow
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Handle,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.Email,
	)
	return i, err
}

const setCommentsEnabled = `-- name: SetCommentsEnabled :exec
UPDATE events SET comments_enabled = $2 WHERE id = $1
`

type SetCommentsEnabledParams struct {
	ID              pgtype.UUID `json:"id"`
	CommentsEnabled bool        `json:"comments_enabled"`
}

func (q *Queries) SetCommentsEnabled(ctx context.Context, arg SetCommentsEnabledParams) error {
	_, err := q.db.Exec(ctx, setCommentsEnabled, arg.ID, arg.CommentsEnabled)
	return err
}

const setEventDraft = `-- name: SetEventDraft :one
UPDATE events
SET status = CASE WHEN $2::bool THEN 'draft'
                  WHEN starts_at IS NOT NULL THEN 'scheduled'
                  ELSE 'polling' END
WHERE id = $1
RETURNING id, host_id, title, event_type, description,
          location_mode, location_address, scheduling_mode, starts_at, status, created_at, comments_enabled, group_id, series_id, recurrence, reminder_sent, visibility, topic, city, custom_emoji, custom_label, general_scope, photo_url, theme, timezone, ends_at, poll_deadline, poll_ready_sent, vote_reminder_sent, quorum_sent, capacity
`

type SetEventDraftParams struct {
	ID      pgtype.UUID `json:"id"`
	Column2 bool        `json:"column_2"`
}

// Park / publish an event. Publishing derives the live status: a concrete
// start time means scheduled, otherwise the poll resumes.
func (q *Queries) SetEventDraft(ctx context.Context, arg SetEventDraftParams) (Event, error) {
	row := q.db.QueryRow(ctx, setEventDraft, arg.ID, arg.Column2)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Title,
		&i.EventType,
		&i.Description,
		&i.LocationMode,
		&i.LocationAddress,
		&i.SchedulingMode,
		&i.StartsAt,
		&i.Status,
		&i.CreatedAt,
		&i.CommentsEnabled,
		&i.GroupID,
		&i.SeriesID,
		&i.Recurrence,
		&i.ReminderSent,
		&i.Visibility,
		&i.Topic,
		&i.City,
		&i.CustomEmoji,
		&i.CustomLabel,
		&i.GeneralScope,
		&i.PhotoUrl,
		&i.Theme,
		&i.Timezone,
		&i.EndsAt,
		&i.PollDeadline,
		&i.PollReadySent,
		&i.VoteReminderSent,
		&i.QuorumSent,
		&i.Capacity,
	)
	return i, err
}

const setEventHost = `-- name: SetEventHost :exec
UPDATE events SET host_id = $2 WHERE id = $1
`

type SetEventHostParams struct {
	ID     pgtype.UUID `json:"id"`
	HostID string      `json:"host_id"`
}

// Hand an event to another host (the UCB sync bot adopts scraped series;
// the previous host stays on as cohost - see ucbsync.go).
func (q *Queries) SetEventHost(ctx context.Context, arg SetEventHostParams) error {
	_, err := q.db.Exec(ctx, setEventHost, arg.ID, arg.HostID)
	return err
}

const setEventLook = `-- name: SetEventLook :exec
UPDATE events SET photo_url = $2, theme = $3 WHERE id = $1
`

type SetEventLookParams struct {
	ID       pgtype.UUID `json:"id"`
	PhotoUrl string      `json:"photo_url"`
	Theme    string      `json:"theme"`
}

// Carry cover + theme onto a sync-created sibling occurrence (CreateEvent
// has no photo/theme params - those normally arrive via the edit PUT).
func (q *Queries) SetEventLook(ctx context.Context, arg SetEventLookParams) error {
	_, err := q.db.Exec(ctx, setEventLook, arg.ID, arg.PhotoUrl, arg.Theme)
	return err
}

const setPollTimeGrid = `-- name: SetPollTimeGrid :exec
INSERT INTO event_poll_time_grid (event_id, start_min, end_min, slot_min)
VALUES ($1, $2, $3, $4)
ON CONFLICT (event_id) DO UPDATE
    SET start_min = EXCLUDED.start_min, end_min = EXCLUDED.end_min, slot_min = EXCLUDED.slot_min
`

type SetPollTimeGridParams struct {
	EventID  pgtype.UUID `json:"event_id"`
	StartMin int32       `json:"start_min"`
	EndMin   int32       `json:"end_min"`
	SlotMin  int32       `json:"slot_min"`
}

func (q *Queries) SetPollTimeGrid(ctx context.Context, arg SetPollTimeGridParams) error {
	_, err := q.db.Exec(ctx, setPollTimeGrid,
		arg.EventID,
		arg.StartMin,
		arg.EndMin,
		arg.SlotMin,
	)
	return err
}

const setProfileEmail = `-- name: SetProfileEmail :one
UPDATE profiles SET email = $2 WHERE user_id = $1
RETURNING user_id, display_name, handle, avatar_url, created_at, email
`

type SetProfileEmailParams struct {
	UserID string `json:"user_id"`
	Email  string `json:"email"`
}

type SetProfileEmailRow struct {
	UserID      string             `json:"user_id"`
	DisplayName string             `json:"display_name"`
	Handle      string             `json:"handle"`
	AvatarUrl   string             `json:"avatar_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Email       string             `json:"email"`
}

func (q *Queries) SetProfileEmail(ctx context.Context, arg SetProfileEmailParams) (SetProfileEmailRow, error) {
	row := q.db.QueryRow(ctx, setProfileEmail, arg.UserID, arg.Email)
	var i SetProfileEmailRow
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Handle,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.Email,
	)
	return i, err
}

const setRsvpAnonymous = `-- name: SetRsvpAnonymous :exec
UPDATE event_attendees SET anonymous = $3 WHERE event_id = $1 AND user_id = $2
`

type SetRsvpAnonymousParams struct {
	EventID   pgtype.UUID `json:"event_id"`
	UserID    string      `json:"user_id"`
	Anonymous bool        `json:"anonymous"`
}

// The anonymity toggle, separate from UpsertRsvp so flipping it never trips
// the changed-rsvp notify path, and so email-link re-RSVPs (which don't send
// the flag) leave a stored choice alone.
func (q *Queries) SetRsvpAnonymous(ctx context.Context, arg SetRsvpAnonymousParams) error {
	_, err := q.db.Exec(ctx, setRsvpAnonymous, arg.EventID, arg.UserID, arg.Anonymous)
	return err
}

const setSeries = `-- name: SetSeries :exec
UPDATE events SET series_id = $2, recurrence = $3 WHERE id = $1
`

type SetSeriesParams struct {
	ID         pgtype.UUID `json:"id"`
	SeriesID   pgtype.UUID `json:"series_id"`
	Recurrence string      `json:"recurrence"`
}

// Attach an event to a series after the fact (multi-date finalize).
func (q *Queries) SetSeries(ctx context.Context, arg SetSeriesParams) error {
	_, err := q.db.Exec(ctx, setSeries, arg.ID, arg.SeriesID, arg.Recurrence)
	return err
}

const topHostsSince = `-- name: TopHostsSince :many
SELECT e.host_id,
       count(*)::int AS events_created,
       coalesce((SELECT count(*) FROM event_invites i WHERE i.inviter_id = e.host_id AND i.created_at >= $1), 0)::int AS invites_sent,
       coalesce(p.display_name, '') AS display_name
FROM events e
LEFT JOIN profiles p ON p.user_id = e.host_id
WHERE e.created_at >= $1
GROUP BY e.host_id, p.display_name
ORDER BY events_created DESC, invites_sent DESC
LIMIT 5
`

type TopHostsSinceRow struct {
	HostID        string `json:"host_id"`
	EventsCreated int32  `json:"events_created"`
	InvitesSent   int32  `json:"invites_sent"`
	DisplayName   string `json:"display_name"`
}

// Digest leaderboard: who created events in the window and how many people
// they pulled in (invites sent).
func (q *Queries) TopHostsSince(ctx context.Context, createdAt pgtype.Timestamptz) ([]TopHostsSinceRow, error) {
	rows, err := q.db.Query(ctx, topHostsSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopHostsSinceRow{}
	for rows.Next() {
		var i TopHostsSinceRow
		if err := rows.Scan(
			&i.HostID,
			&i.EventsCreated,
			&i.InvitesSent,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET title = $2, description = $3, location_mode = $4, location_address = $5,
    visibility = $6, topic = $7, city = $8, photo_url = $9, theme = $10,
    starts_at = $11, reminder_sent = $12, ends_at = $13, poll_deadline = $14, capacity = $15
WHERE id = $1
RETURNING id, host_id, title, event_type, description,
          location_mode, location_address, scheduling_mode, starts_at, status, created_at, comments_enabled, group_id, series_id, recurrence, reminder_sent, visibility, topic, city, custom_emoji, custom_label, general_scope, photo_url, theme, timezone, ends_at, poll_deadline, poll_ready_sent, vote_reminder_sent, quorum_sent, capacity
`

type UpdateEventParams struct {
	ID              pgtype.UUID        `json:"id"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	LocationMode    string             `json:"location_mode"`
	LocationAddress string             `json:"location_address"`
	Visibility      string             `json:"visibility"`
	Topic           string             `json:"topic"`
	City            string             `json:"city"`
	PhotoUrl        string             `json:"photo_url"`
	Theme           string             `json:"theme"`
	StartsAt        pgtype.Timestamptz `json:"starts_at"`
	ReminderSent    bool               `json:"reminder_sent"`
	EndsAt          pgtype.Timestamptz `json:"ends_at"`
	PollDeadline    pgtype.Timestamptz `json:"poll_deadline"`
	Capacity        int32              `json:"capacity"`
}

// starts_at + reminder_sent are set by the handler: the time stays editable
// after finalize, and rescheduling resets reminder_sent so the day-before
// reminder re-fires for the new date.
func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.LocationMode,
		arg.LocationAddress,
		arg.Visibility,
		arg.Topic,
		arg.City,
		arg.PhotoUrl,
		arg.Theme,
		arg.StartsAt,
		arg.ReminderSent,
		arg.EndsAt,
		arg.PollDeadline,
		arg.Capacity,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Title,
		&i.EventType,
		&i.Description,
		&i.LocationMode,
		&i.LocationAddress,
		&i.SchedulingMode,
		&i.StartsAt,
		&i.Status,
		&i.CreatedAt,
		&i.CommentsEnabled,
		&i.GroupID,
		&i.SeriesID,
		&i.Recurrence,
		&i.ReminderSent,
		&i.Visibility,
		&i.Topic,
		&i.City,
		&i.CustomEmoji,
		&i.CustomLabel,
		&i.GeneralScope,
		&i.PhotoUrl,
		&i.Theme,
		&i.Timezone,
		&i.EndsAt,
		&i.PollDeadline,
		&i.PollReadySent,
		&i.VoteReminderSent,
		&i.QuorumSent,
		&i.Capacity,
	)
	return i, err
}

const upsertAvailabilityDayFree = `-- name: UpsertAvailabilityDayFree :exec
INSERT INTO availability_days (user_id, day, daypart, status)
VALUES ($1, $2, $3, 'free')
ON CONFLICT (user_id, day, daypart) DO UPDATE SET status = 'free'
`

type UpsertAvailabilityDayFreeParams struct {
	UserID  string      `json:"user_id"`
	Day     pgtype.Date `json:"day"`
	Daypart string      `json:"daypart"`
}

// Poll picks flow back into MAIN availability: a concrete dayslot vote marks
// that cell free (overwriting a stale busy - the guest just said they can).
func (q *Queries) UpsertAvailabilityDayFree(ctx context.Context, arg UpsertAvailabilityDayFreeParams) error {
	_, err := q.db.Exec(ctx, upsertAvailabilityDayFree, arg.UserID, arg.Day, arg.Daypart)
	return err
}

const upsertPreferenceAnswer = `-- name: UpsertPreferenceAnswer :one

INSERT INTO event_preference_answers (event_id, user_id, question_key, answer)
VALUES ($1, $2, $3, $4)
ON CONFLICT (event_id, user_id, question_key) DO UPDATE
    SET answer = EXCLUDED.answer
RETURNING id, event_id, user_id, question_key, answer
`

type UpsertPreferenceAnswerParams struct {
	EventID     pgtype.UUID `json:"event_id"`
	UserID      string      `json:"user_id"`
	QuestionKey string      `json:"question_key"`
	Answer      string      `json:"answer"`
}

// ===================== preference answers =========================
func (q *Queries) UpsertPreferenceAnswer(ctx context.Context, arg UpsertPreferenceAnswerParams) (EventPreferenceAnswer, error) {
	row := q.db.QueryRow(ctx, upsertPreferenceAnswer,
		arg.EventID,
		arg.UserID,
		arg.QuestionKey,
		arg.Answer,
	)
	var i EventPreferenceAnswer
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.QuestionKey,
		&i.Answer,
	)
	return i, err
}

const upsertProfile = `-- name: UpsertProfile :one
INSERT INTO profiles (user_id, display_name, handle)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE
    SET display_name = EXCLUDED.display_name,
        handle       = EXCLUDED.handle
RETURNING user_id, display_name, handle, avatar_url, created_at, email
`

type UpsertProfileParams struct {
	UserID      string `json:"user_id"`
	DisplayName string `json:"display_name"`
	Handle      string `json:"handle"`
}

type UpsertProfileRow struct {
	UserID      string             `json:"user_id"`
	DisplayName string             `json:"display_name"`
	Handle      string             `json:"handle"`
	AvatarUrl   string             `json:"avatar_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Email       string             `json:"email"`
}

// Name + handle only. Email is owned by the auth provider (Clerk) and synced
// separately via SetProfileEmail, so a profile edit never clobbers it.
func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) (UpsertProfileRow, error) {
	row := q.db.QueryRow(ctx, upsertProfile, arg.UserID, arg.DisplayName, arg.Handle)
	var i UpsertProfileRow
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Handle,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.Email,
	)
	return i, err
}

const upsertRsvp = `-- name: UpsertRsvp :one

INSERT INTO event_attendees (event_id, user_id, rsvp, anonymous)
VALUES ($1, $2, $3, $4)
ON CONFLICT (event_id, user_id) DO UPDATE
    SET rsvp = EXCLUDED.rsvp
    WHERE event_attendees.rsvp IS DISTINCT FROM EXCLUDED.rsvp
RETURNING id, event_id, user_id, rsvp, created_at, anonymous
`

type UpsertRsvpParams struct {
	EventID   pgtype.UUID `json:"event_id"`
	UserID    string      `json:"user_id"`
	Rsvp      string      `json:"rsvp"`
	Anonymous bool        `json:"anonymous"`
}

// ========================= attendees ==============================
// Returns a row ONLY when the rsvp actually changed (a fresh INSERT, or an
// UPDATE to a different value). A no-op re-submit of the same rsvp updates
// nothing and returns no row, so the handler (treating pgx.ErrNoRows as
// "unchanged") won't re-notify the host. Race-safe: concurrent conflicting
// upserts serialize on the (event_id,user_id) unique index, so a second
// identical "going" sees the just-committed row and its WHERE is false.
func (q *Queries) UpsertRsvp(ctx context.Context, arg UpsertRsvpParams) (EventAttendee, error) {
	row := q.db.QueryRow(ctx, upsertRsvp,
		arg.EventID,
		arg.UserID,
		arg.Rsvp,
		arg.Anonymous,
	)
	var i EventAttendee
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Rsvp,
		&i.CreatedAt,
		&i.Anonymous,
	)
	return i, err
}

const upsertVote = `-- name: UpsertVote :one
INSERT INTO event_time_votes (option_id, user_id, response)
VALUES ($1, $2, $3)
ON CONFLICT (option_id, user_id) DO UPDATE
    SET response = EXCLUDED.response
RETURNING id, option_id, user_id, response
`

type UpsertVoteParams struct {
	OptionID pgtype.UUID `json:"option_id"`
	UserID   string      `json:"user_id"`
	Response string      `json:"response"`
}

func (q *Queries) UpsertVote(ctx context.Context, arg UpsertVoteParams) (EventTimeVote, error) {
	row := q.db.QueryRow(ctx, upsertVote, arg.OptionID, arg.UserID, arg.Response)
	var i EventTimeVote
	err := row.Scan(
		&i.ID,
		&i.OptionID,
		&i.UserID,
		&i.Response,
	)
	return i, err
}
